(function(g){'use strict';
const C=g.GameCore,D=g.GameData,E=g.GameExtensions,I=g.VoxelIcons;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>Number.isFinite(Number(v))?new Intl.NumberFormat('zh-TW',{maximumFractionDigits:Math.abs(v)<10?1:0,notation:Math.abs(v)>=1e6?'compact':'standard'}).format(v):'—';
const pct=(a,b)=>Math.max(0,Math.min(100,100*(Number(a)||0)/(Number(b)||1)));
const names={gold:'金幣',gems:'寶石',tickets:'招募券',honor:'榮譽',books:'技能書',fragments:'獵人碎片',badges:'傳說徽章',kingCoins:'王者幣',swapStones:'置換石',points:'活動點數',hp:'生命藥水',mp:'魔力藥水',attack:'力量藥劑',xp:'經驗藥劑',hourglass:'時光沙漏',goldBag:'金幣袋',...D.materials};
const navs=[['castle','城堡'],['hunt','狩獵'],['heroes','獵人'],['equipment','裝備'],['quests','任務'],['challenges','挑戰'],['shop','商店'],['settings','設定']];
const prefKey='canglan-preferences-v1',saveKey='canglan-save-v1';
let prefs={sound:.35,music:0,hour:14,orbit:false,cut:false,lightCycle:false,particles:1,contrast:false,textScale:1,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
try{Object.assign(prefs,JSON.parse(localStorage.getItem(prefKey)||'{}'));}catch(_){}
let state,saveProblem='',offlineSummary=null;
try{const raw=localStorage.getItem(saveKey);if(raw){const parsed=JSON.parse(raw),v=C.migrate(parsed);if(!v.ok)throw Error(v.message);state=parsed;E.init(state);offlineSummary=C.offline(state,Date.now());}}catch(e){saveProblem='舊存檔讀取失敗，已保留原資料。可在設定匯出備份。'+e.message;}
if(!state)state=C.create();
let page='castle',selectedHero=null,selectedItem=null,selectedBuilding=null,sub='main',inventoryFilter='all',questGroup='main',worldView='castle',world,dirty=true,lastPanel=0,lastHud=0,lastWorld=0,lastSave=0,audioContext=null,inspect=false,dialogCallback=null,raf=0,destroyed=false;
const img=(id,cls='')=>`<img src="${I.icon(id)}" class="${cls}" alt="" draggable="false">`;
const button=(label,type,payload={},cls='',disabled=false)=>`<button class="button ${cls}" data-action="${esc(type)}" data-payload="${esc(JSON.stringify(payload))}" ${disabled?'disabled':''}>${esc(label)}</button>`;
const uiButton=(label,action,payload={},cls='',disabled=false)=>`<button class="button ${cls}" data-ui="${esc(action)}" data-payload="${esc(JSON.stringify(payload))}" ${disabled?'disabled':''}>${esc(label)}</button>`;
const link=(label,to,cls='')=>`<button class="button ${cls}" data-nav="${esc(to)}">${esc(label)}</button>`;
const bar=(value,max,cls='')=>`<div class="bar ${cls}"><i style="width:${pct(value,max)}%"></i></div>`;
const heading=(title,desc='',eyebrow='蒼嵐堡 · 獵人公會')=>`<div class="panel-heading"><span class="eyebrow">${esc(eyebrow)}</span><h2>${esc(title)}</h2>${desc?`<p class="subline">${esc(desc)}</p>`:''}</div>`;
const section=(title,content,extra='')=>`<section class="section"><div class="section-head"><h3>${esc(title)}</h3>${extra}</div>${content}</section>`;
const stat=(label,value)=>`<div class="stat-pair"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;
const feature=(a,b)=>`<div class="feature-row"><span>${esc(a)}</span><span>${esc(b)}</span></div>`;
const duration=seconds=>{seconds=Math.max(0,Math.floor(seconds||0));return seconds>=3600?`${Math.floor(seconds/3600)} 小時 ${Math.floor(seconds%3600/60)} 分`:seconds>=60?`${Math.floor(seconds/60)} 分 ${seconds%60} 秒`:`${seconds} 秒`;};
function amounts(obj){if(!obj||typeof obj!=='object')return '';return Object.entries(obj).flatMap(([k,v])=>typeof v==='number'&&v?`${({xp:'經驗',heroXp:'獵人經驗',kingdomXp:'王國經驗'}[k])||names[k]||k} ${fmt(v)}`:v&&typeof v==='object'?amounts(v):[]).filter(Boolean).join(' · ');}
const cost=obj=>`<div class="cost">${amounts(obj)||'無需資源'}</div>`;
const reward=obj=>`<div class="reward">${amounts(obj)}</div>`;
function extView(){try{return E.view(state,Date.now());}catch(e){console.error(e);return {};}}
function toast(message,ok=true){const el=document.createElement('div');el.className='toast'+(ok?'':' error');el.textContent=message||'操作完成';$('#toasts').append(el);setTimeout(()=>el.remove(),4200);}
function tone(ok=true){if(!prefs.sound||!audioContext)return;try{audioContext.resume();const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.setValueAtTime(ok?523:196,audioContext.currentTime);osc.frequency.exponentialRampToValueAtTime(ok?784:147,audioContext.currentTime+.13);gain.gain.setValueAtTime(Number(prefs.sound)*.1,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.25);osc.connect(gain).connect(audioContext.destination);osc.start();osc.stop(audioContext.currentTime+.3);}catch(_){} }
function save(){if(saveProblem)return false;try{const text=JSON.stringify(state);localStorage.setItem(saveKey,text);localStorage.setItem(prefKey,JSON.stringify(prefs));$('#save-indicator').textContent='已保存';return true;}catch(e){$('#save-indicator').textContent='未能保存';return false;}}
function act(type,payload={},quiet=false){try{const result=C.dispatch(state,type,payload,Date.now());if(!quiet)toast(result.message,result.ok);if(result.ok){tone();dirty=true;syncWorld();save();}else tone(false);render(true);return result;}catch(e){console.error(e);toast('操作未完成：'+e.message,false);return {ok:false,message:e.message};}}
function confirm(title,body,callback){const dialog=$('#confirm-dialog');$('#dialog-content').innerHTML=`<h2 id="dialog-title">${esc(title)}</h2>${body}`;dialogCallback=callback;dialog.returnValue='';dialog.showModal();}
$('#confirm-dialog').addEventListener('close',()=>{const cb=dialogCallback;dialogCallback=null;if($('#confirm-dialog').returnValue==='confirm'&&cb)cb($('#dialog-content'));});
function go(to){page=to;sub='main';selectedBuilding=null;if(to!=='heroes')selectedHero=null;if(to!=='equipment')selectedItem=null;worldView=to==='hunt'?'battle':'castle';world?.setView(worldView);$('#panel').scrollTop=0;dirty=true;render(true);}
function syncWorld(){if(world)world.sync(state,{heroStats:C.heroStats,team:C.team,teamPower:C.teamPower});}
function paint(selector,html){const el=$(selector);if(el.innerHTML!==html)el.innerHTML=html;}
function renderHUD(){
paint('#resource-bar',['gold','gems','tickets','honor'].map(k=>`<div class="resource" title="${esc(names[k])}">${img(k)}<div><span class="amount">${fmt(state.resources[k])}</span><span class="label">${names[k]}</span></div></div>`).join(''));
paint('#navigation',navs.map(([id,name],i)=>`<button class="nav-button ${i>4?'extra':''} ${page===id?'active':''}" data-nav="${id}" ${page===id?'aria-current="page"':''}>${img(id)}<span>${name}</span></button>`).join(''));
const cap=C.capacity(state),t=state.teams[state.selectedTeam]||[];
paint('#party-dock',Array.from({length:cap.slots},(_,i)=>{const h=state.heroes.find(h=>h.id===t[i]);if(!h)return `<button class="party-slot empty" data-ui="formation">＋<span class="party-name">${i<2?'前排':'後排'}</span></button>`;const s=C.heroStats(state,h);return `<button class="party-slot" data-hero="${esc(h.id)}" aria-label="${esc(h.name)} 等級 ${h.level}">${img(h.classId)}<div class="party-name">${esc(h.name)}</div><div class="party-level">Lv.${h.level} · ${i<2?'前排':'後排'}</div>${bar(h.hp,s.maxHp)}</button>`;}).join(''));
$('#world-eyebrow').textContent=`王國 LV.${state.kingdom.level} · ${state.ascensions||0} 次飛升`;
const zone=D.zones[(state.hunting.zone||1)-1],enemy=state.hunting.enemy;
$('#world-title').textContent=worldView==='map'?'十境遠征':worldView==='battle'?zone.name:'蒼嵐堡';
$('#world-subtitle').textContent=worldView==='map'?'從翠綠草原，走向神話之域。':worldView==='battle'?`第 ${state.hunting.zone} 境 · 關卡 ${state.hunting.stage} / 10`:'層層城牆之內，為下一段旅程做好準備。';
$('#scene-badge').textContent=state.hunting.active?'狩獵中 · '+state.hunting.speed+'×':state.hunting.restUntil>Date.now()?'隊伍休整中':'公會待命';
$('#battle-overlay').hidden=worldView!=='battle'||!enemy;
if(worldView==='battle'&&enemy)paint('#battle-overlay',`<div class="enemy-title"><strong>${esc(enemy.name)}</strong><span>${enemy.boss?'首領':enemy.elite?'精英':'野外魔物'}</span></div>${bar(enemy.hp,enemy.maxHp,'red')}<div class="hp-label">${fmt(enemy.hp)} / ${fmt(enemy.maxHp)}</div><div class="mechanic">${esc(D.mechanicNames?.[enemy.mechanic]||'')}</div>`);
$('#clock-display').textContent=`${String(Math.floor(prefs.hour)).padStart(2,'0')}:${String(Math.floor((prefs.hour%1)*60)).padStart(2,'0')} · ${prefs.hour<6||prefs.hour>19?'夜間':prefs.hour>16?'黃昏':'白晝'}`;
$('#world-hint').textContent=inspect?'拖曳環繞 · 滾輪縮放 · 點擊選取':'拖曳平移 · 滾輪縮放 · 點擊建築';
$('.world-pane').classList.toggle('battle',worldView==='battle');
renderRibbonLedger();
}
function renderRibbonLedger(){
const v=extView(),cap=C.capacity(state),main=(v.tasks||[]).find(t=>t.group==='main'&&!t.claimed);
paint('#quest-ribbon',`<span>${esc(main?.name||'讓公會持續成長')}</span>`);
paint('#stat-ledger',[['weapon','隊伍戰力',fmt(C.teamPower(state))],['castle','王國等級','Lv.'+state.kingdom.level],['heroes','公會獵人',`${state.heroes.length} / ${cap.roster}`],['hunt','最遠探索',`${state.progress.maxZone} - ${state.progress.maxStage}`],['gold','金幣',fmt(state.resources.gold)]].map(([icon,label,value])=>`<div class="ledger-row">${img(icon)}<span class="ledger-text"><span class="ledger-label">${esc(label)}</span><span class="ledger-value">${esc(value)}</span></span></div>`).join(''));
renderWorldLabels();
}
const plateNames={castle:'王城',tavern:'酒館',warehouse:'倉庫',training:'訓練場',forge:'鐵匠鋪',potion:'藥水工坊',gem:'寶石工坊',market:'市場',library:'圖書館',altar:'昇華祭壇'};
function renderWorldLabels(){
const box=$('#world-labels');if(!box)return;
if(world?.getMarkers){
const zoneLabels=worldView!=='castle';
let markers=[];try{markers=world.getMarkers().filter(m=>m.visible&&(zoneLabels?m.kind!=='building':m.kind==='building')&&(zoneLabels||innerWidth>780||m.level||inspect));}catch(_){markers=[];}
paint('#world-labels',markers.map(m=>zoneLabels
  ?`<button class="world-label ${m.locked?'unbuilt':''}" data-zone="${esc(m.id)}" style="left:${Math.round(m.x)}px;top:${Math.round(m.y)}px" aria-label="${esc(m.label)}${m.locked?' 尚未解鎖':'，點擊前往狩獵'}"><span class="plate">${esc(m.label)}</span></button>`
  :`<button class="world-label ${m.level?'':'unbuilt'}" data-building="${esc(m.id)}" style="left:${Math.round(m.x)}px;top:${Math.round(m.y)}px" aria-label="${esc(plateNames[m.id]||m.label)}${m.level?' 等級 '+m.level:' 尚未建造'}"><span class="plate">${esc(plateNames[m.id]||m.label)}</span><span class="badge">${img(m.id)}</span></button>`).join(''));
renderSelectionCard(markers);return;}
paint('#world-labels','');
}
function renderSelectionCard(markers){
const card=$('#world-selection');if(!card)return;
const target=selectedBuilding?(markers||[]).find(m=>m.id===selectedBuilding):null;
if(worldView!=='castle'||!target){card.hidden=true;card.innerHTML='';return;}
const b=(extView().buildings||[]).find(x=>x.id===selectedBuilding)||{};
card.hidden=false;card.style.left=Math.round(target.x)+'px';card.style.top=Math.round(target.y-46)+'px';
paint('#world-selection',`<button class="card" data-building="${esc(selectedBuilding)}" aria-label="開啟${esc(plateNames[selectedBuilding]||selectedBuilding)}面板"><span class="card-head">${img(selectedBuilding)}<span><span class="card-name">${esc(plateNames[selectedBuilding]||selectedBuilding)}</span><span class="card-sub">${b.level?'目前 Lv.'+b.level:'尚未建造'}</span></span></span><span class="card-bar">${esc(b.effect||b.description||'點擊開啟設施面板')}</span></button><span class="card-tail"></span>`);
}
function render(force=false){renderHUD();if(!force&&!dirty&&performance.now()-lastPanel<1300)return;if(!force&&$('#panel').contains(document.activeElement)&&/INPUT|SELECT|TEXTAREA/.test(document.activeElement.tagName))return;
const scroll=$('#panel').scrollTop;let html='';
const renders={castle:renderCastle,hunt:renderHunt,heroes:renderHeroes,equipment:renderEquipment,quests:renderQuests,shop:renderShop,challenges:renderChallenges,settings:renderSettings,wanderers:renderWanderers,expeditions:renderExpeditions,guild:renderGuild,artifacts:renderArtifacts,collections:renderCollections,building:renderBuilding,research:renderResearch,resonance:renderResonance};
try{html=(renders[page]||renderCastle)();}catch(e){console.error(e);html=heading('面板暫時無法顯示',e.message)+link('返回城堡','castle');}
const panel=$('#panel');if(panel.innerHTML!==html){panel.innerHTML=html;panel.scrollTop=scroll;}dirty=false;lastPanel=performance.now();
}
function renderCastle(){const v=extView(),cap=C.capacity(state),main=(v.tasks||[]).find(t=>t.group==='main'&&!t.claimed);
return heading('今天，從城堡出發','招募夥伴、派出獵隊，讓每次遠征都帶回新的可能。','YOUR KINGDOM')+
`<div class="goal-box"><h3>${esc(main?.name||'讓公會持續成長')}</h3><p>${esc(main?.description||'升級王國與建築，開拓十個截然不同的狩獵地區。')}</p>${main?bar(main.progress,main.target):''}<div class="button-row" style="margin-top:12px">${main?.ready?button('領取獎勵','quest',{kind:'main',id:main.id},'gold'):link('查看任務','quests','small ghost')}</div></div>`+
`<div class="stat-grid">${stat('隊伍戰力',fmt(C.teamPower(state)))}${stat('最遠探索',`${state.progress.maxZone} - ${state.progress.maxStage}`)}${stat('公會獵人',`${state.heroes.length} / ${cap.roster}`)}${stat('王國經驗',`${fmt(state.kingdom.xp)} / ${fmt(C.kingdomXP(state.kingdom.level))}`)}</div>`+
`<div class="button-row">${state.hunting.active?link('查看狩獵','hunt','primary'):uiButton('派出獵隊','depart',{},'primary')}${link('招募夥伴','heroes')}</div>`+
section('城堡設施',`<div class="building-list">${(v.buildings||[]).map(b=>`<button class="building-row" data-building="${b.id}">${img(b.id)}<span><strong>${esc(b.name)}</strong><small>${esc(b.effect||b.description||'城堡設施')}</small></span><span class="level">${b.level?'LV.'+b.level:'待建造'}</span></button>`).join('')}</div>`)+
section('公會生活',`<div class="button-row">${link('流浪獵人','wanderers')}${link('遠征委託','expeditions')}</div><div class="button-row" style="margin-top:8px">${link('公會殿堂','guild')}${link('神器與徽章','artifacts')}</div><div class="button-row" style="margin-top:8px">${link('收藏圖鑑','collections')}${link('共鳴水晶','resonance')}</div>`)+
section('探索與傳承',`<div class="button-row">${link('挑戰秘境','challenges')}${link('城堡市集','shop')}${link('學識與飛升','research')}</div>`)+
section('城堡記事',(state.events||[]).slice(-6).reverse().map(e=>`<div class="log-row ${esc(e.type)}">${esc(e.text)}</div>`).join('')||'<p class="empty-note">你的公會故事即將開始。</p>');}
function renderBuilding(){const b=(extView().buildings||[]).find(b=>b.id===selectedBuilding);if(!b)return renderCastle();const destinations={castle:['獵隊編制','heroes'],tavern:['招募獵人','heroes'],warehouse:['管理裝備','equipment'],training:['訓練獵人','heroes'],forge:['鍛造與強化','equipment'],potion:['藥水與補給','shop'],gem:['寶石工坊','equipment'],market:['城堡市集','shop'],library:['學院研究','research'],altar:['榮譽與飛升','research']},d=destinations[b.id];
return link('← 返回城堡','castle','ghost')+heading(b.name,b.description||'城堡裡的每一座建築，都為獵隊帶來新的力量。')+`<div class="building-detail-illustration">${img(b.id)}</div>`+feature('目前等級',b.level+' / '+b.maxLevel)+feature('目前效果',b.effect||'尚未建造')+feature('下一級',b.nextEffect||b.reason||'已達最高等級')+section(b.level?'升級建築':'建造設施',cost(b.cost)+button(b.level?'升級至 LV.'+(b.level+1):'開始建造','building',{id:b.id},'primary wide',b.locked||b.level>=b.maxLevel)+(b.reason?`<p class="subline">${esc(b.reason)}</p>`:''))+section('設施功能',link(d[0],d[1],'wide'))+uiButton('移動鏡頭至建築','focus',{id:b.id},'ghost wide');}
function renderHunt(){const h=state.hunting,cap=C.capacity(state),enemy=C.enemyPreview(state,h.zone,h.stage,h.difficulty),report=h.report||{};
return heading('遠征與狩獵','戰鬥自動進行。適時更換裝備、培養夥伴與調整前後排。','THE HUNT')+
`<div class="form-grid"><label class="field">狩獵地區<select data-change="zone">${D.zones.map(z=>`<option value="${z.id}" ${z.id===h.zone?'selected':''} ${z.id>state.progress.maxZone?'disabled':''}>${z.id}. ${z.name}${z.id>state.progress.maxZone?' · 未解鎖':''}</option>`).join('')}</select></label><label class="field">關卡<select data-change="stage">${Array.from({length:10},(_,i)=>`<option value="${i+1}" ${i+1===h.stage?'selected':''} ${h.zone===state.progress.maxZone&&i+1>state.progress.maxStage?'disabled':''}>${i+1===10?'首領':i+1+' / 10'}</option>`).join('')}</select></label></div>`+
`<div class="tabs">${(D.difficulties||[]).map(d=>button(d.name,'target',{zone:h.zone,stage:h.stage,difficulty:d.id},`small ${h.difficulty===d.id?'primary':''}`,h.active)).join('')}</div>`+
`<div class="battle-stats"><div class="row between"><strong>${esc(h.enemy?.name||enemy?.name||'等待出發')}</strong><span class="pill">${h.mode==='abyss'?'深淵 '+h.abyssFloor+' 層':'第 '+h.zone+' 境'}</span></div>${feature('狀態',h.active?'自動狩獵中':h.restUntil>Date.now()?'休整剩餘 '+duration((h.restUntil-Date.now())/1000):'城堡內恢復生命與魔力')}${feature('敵方攻擊 / 防禦',fmt(enemy?.attack)+' / '+fmt(enemy?.defense))}${feature('隊伍戰力',fmt(C.teamPower(state,h.active?h.team:state.selectedTeam)))}</div>`+
`<div class="button-row">${h.active?button('召回城堡','recall',{},'primary'):button('開始狩獵','dispatch',{},'primary',h.restUntil>Date.now())}${uiButton('查看世界地圖','map')}</div>`+
`<div class="tabs">${[1,2,4].map(value=>button(value+'×','speed',{value},`small ${h.speed===value?'primary':''}`)).join('')}</div>`+
`<div class="check-grid"><label><input type="checkbox" data-change="autoNext" ${h.autoNext?'checked':''}>通關後前往下一關</label><label><input type="checkbox" data-change="autoContinue" ${h.autoContinue?'checked':''}>休整後繼續狩獵</label><label><input type="checkbox" data-change="autoPotion" ${state.autoPotion.enabled?'checked':''}>自動補充藥水（生命低於 ${Math.round(state.autoPotion.hp*100)}%）</label></div>`+
section('隊伍編制',formation(),button('自動編隊','autoTeam',{},'small'))+
section('戰鬥統計',C.team(state,h.active?h.team:state.selectedTeam).map(hero=>{const r=report[hero.id]||{};return feature(hero.name,`傷害 ${fmt(r.damage||0)} · 治療 ${fmt(r.healing||0)}`);}).join(''))+
section('即時戰報',(state.events||[]).filter(e=>['combat','skill','loot','boss','death','kill','rest','damage','heal'].includes(e.type)).slice(-14).reverse().map(e=>`<div class="log-row ${esc(e.type)}">${esc(e.text)}</div>`).join('')||'<p class="empty-note">出發後，戰鬥與掉落會記錄在這裡。</p>');}
function formation(){const cap=C.capacity(state),t=state.teams[state.selectedTeam]||[];return `<div class="tabs">${Array.from({length:cap.teams},(_,index)=>button('隊伍 '+(index+1),'selectTeam',{index},`small ${state.selectedTeam===index?'primary':''}`)).join('')}</div><div class="formation">${Array.from({length:cap.slots},(_,slot)=>`<label class="formation-slot ${slot>1?'rear':''}"><span>${slot<2?'前排':'後排'} ${slot+1}</span><select data-change="assign" data-slot="${slot}"><option value="">空位</option>${state.heroes.map(hero=>`<option value="${esc(hero.id)}" ${t[slot]===hero.id?'selected':''}>${esc(hero.name)} Lv.${hero.level}</option>`).join('')}</select></label>`).join('')}</div><p class="subline">前兩格優先承受攻擊；建議把騎士與劍士放在前排。</p>`;}
function renderHeroes(){const hero=state.heroes.find(h=>h.id===selectedHero);if(hero)return renderHero(hero);const cap=C.capacity(state);
return heading('獵人公會','六種職業，各司其職。每位獵人都有自己的成長路線。','THE GUILD')+
section('招募新夥伴',`<div class="stack">${[['normal','一般招募'],['advanced','高級招募'],['mythic','神話招募']].map(([kind,label])=>`<div class="row between"><div><strong class="small">${label}</strong>${cost(C.recruitCost(state,kind))}<small class="muted">${kind==='normal'?'★1–3':kind==='advanced'?`★2–5 · ${state.recruitment.advancedPity}/10 保底`:`★3–6 · ${state.recruitment.mythicPity}/20 保底`}</small></div>${button('招募','recruit',{kind},'small',state.heroes.length>=cap.roster)}</div>`).join('')}</div>`+uiButton('設定心願職業','wishlist',{},'ghost'))+
section(`公會名冊 ${state.heroes.length} / ${cap.roster}`,`<div class="stack">${state.heroes.map(h=>{const s=C.heroStats(state,h);return `<button class="hero-card" data-hero="${esc(h.id)}">${img(h.classId)}<div><div class="name">${esc(h.name)} ${h.locked?'· 鎖定':''}</div><div class="stars">${'★'.repeat(h.stars)}</div><div class="meta">${D.classes[h.classId].name} · Lv.${h.level} · 戰力 ${fmt(s.power)}</div></div><span class="pill ${C.occupied(state,h)?'gold':''}">${h.expeditionId?'遠征中':C.occupied(state,h)?'狩獵中':'待命'}</span></button>`;}).join('')}</div>`)+
section('編隊',formation(),button('自動編隊','autoTeam',{},'small'))+
section('碎片合成',`<div class="form-grid"><label class="field">職業<select id="synth-class">${D.classList.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></label><label class="field">星級<select id="synth-stars"><option value="4">★★★★</option><option value="5">★★★★★</option></select></label></div><p class="subline">消耗獵人碎片，依每週合成次數限制製作指定職業。</p>${uiButton('合成獵人','synth',{},'wide')}`);}
function renderHero(h){const s=C.heroStats(state,h),cls=D.classes[h.classId],busy=C.occupied(state,h),training=C.trainingCost(h),equip=h.equipment||{};
const skills=cls.skills.map((sk,index)=>`<div class="skill-row"><div class="row between"><strong class="small">${esc(sk.name)} · Lv.${h.skills[index]}</strong><span class="pill ${h.level<sk.unlock?'lock':''}">Lv.${sk.unlock} 解鎖</span></div><p>${sk.mult?`${Math.round(sk.mult*100)}% 攻擊 × ${sk.hits} 次`:'輔助技能'} · ${sk.cooldown} 秒冷卻 · 消耗 ${sk.mp} MP${sk.heal?' · 團隊治療':''}${sk.freeze?' · 凍結 '+sk.freeze+' 秒':''}${sk.dot?' · 持續傷害':''}</p>${button('技能升級','skill',{heroId:h.id,index},'small',h.level<sk.unlock||h.skills[index]>=10)}</div>`).join('');
return uiButton('← 公會名冊','roster',{},'ghost')+heading(h.name,`${cls.name} · ${D.elements?.[cls.element]?.name||cls.element} · ${h.legend?'傳說獵人':'公會獵人'}`)+
`<div class="hero-portrait">${img(h.classId)}<div><div class="stars">${'★'.repeat(h.stars)}</div><h3>Lv.${h.level}</h3><p class="subline">戰力 ${fmt(s.power)}${C.effectiveLevel(state,h)>h.level?' · 共鳴 Lv.'+C.effectiveLevel(state,h):''}</p>${uiButton('更改名字','rename',{heroId:h.id},'small ghost')}</div></div>`+
`<div class="hero-bars"><div><div class="caption"><span>生命</span><span>${fmt(h.hp)} / ${fmt(s.maxHp)}</span></div>${bar(h.hp,s.maxHp)}</div><div><div class="caption"><span>魔力</span><span>${fmt(h.mp)} / ${fmt(s.maxMp)}</span></div>${bar(h.mp,s.maxMp,'mp')}</div><div><div class="caption"><span>經驗</span><span>${fmt(h.xp)} / ${fmt(C.heroXP(h.level))}</span></div>${bar(h.xp,C.heroXP(h.level),'gold')}</div></div>`+
`<div class="stat-grid">${stat('攻擊 / 防禦',fmt(s.attack)+' / '+fmt(s.defense))}${stat('攻速 / 暴擊',fmt(s.speed)+' / '+fmt(s.crit*100)+'%')}</div>`+
section('成長',cost(typeof training==='number'?{gold:training}:training)+`<div class="button-row">${button('訓練 1 級','train',{heroId:h.id},'primary',busy)}${button('訓練 10 級','train',{heroId:h.id,count:10},'',busy)}</div><div class="button-row" style="margin-top:8px">${button('突破','breakthrough',{heroId:h.id},'',busy)}${uiButton('升星','starUp',{heroId:h.id},'',busy)}</div>`)+
section('戰鬥技能',skills+`<div class="form-grid" style="margin-top:12px">${[['main','主動技能',h.mainSkill],['sub','副技能',h.subSkill]].map(([id,label,val])=>`<label class="field">${label}<select data-change="skillSlot" data-slot="${id}" data-hero="${h.id}">${cls.skills.map((sk,i)=>`<option value="${i}" ${val===i?'selected':''}>${esc(sk.name)}</option>`).join('')}</select></label>`).join('')}</div>`)+
section('裝備',`<div class="equipment-grid">${D.slots.map(slot=>{const it=state.inventory.find(i=>i.id===equip[slot.id]);return `<button class="item-tile rarity-${it?.stars||1}" ${it?`data-item="${it.id}"`:`data-ui="equipPicker" data-payload="${esc(JSON.stringify({heroId:h.id,slot:slot.id}))}"`}>${img(slot.id)}<strong>${esc(it?.name||slot.name)}</strong><small>${it?'★'.repeat(it.stars)+' +'+it.enhance:'點擊穿戴'}</small></button>`;}).join('')}</div><div class="button-row" style="margin-top:10px">${button('自動裝備','autoEquip',{heroId:h.id},'small')}${uiButton('選擇裝備','equipPicker',{heroId:h.id},'small')}</div>`)+
section('管理獵人',`<div class="button-row">${button(h.locked?'解除鎖定':'鎖定獵人','lockHero',{heroId:h.id},'small')}${uiButton('重置養成','resetHero',{heroId:h.id},'small',busy)}${uiButton('置換養成','swapHero',{heroId:h.id},'small',busy)}</div><p class="subline">重置、置換與升星前會列出實際消耗對象。被派遣或鎖定的獵人受保護。</p>${uiButton('解僱獵人','dismiss',{heroId:h.id},'danger small',busy||h.locked)}`);}
function itemName(it){return `${it.name} · T${it.tier} ${'★'.repeat(it.stars)} +${it.enhance}`;}
function equippedBy(id){return state.heroes.find(h=>Object.values(h.equipment).includes(id));}
function renderEquipment(){const it=state.inventory.find(i=>i.id===selectedItem);if(it)return renderItem(it);const cap=C.capacity(state),items=state.inventory.filter(i=>inventoryFilter==='all'||i.slot===inventoryFilter).sort((a,b)=>b.tier-a.tier||b.stars-a.stars||b.enhance-a.enhance);
return heading('兵器與補給','以戰利品鍛造新裝備，為每位夥伴找到合適的武器。','THE ARMORY')+
`<div class="tabs">${[['main','裝備'],['craft','鍛造'],['gems','寶石']].map(([id,name])=>uiButton(name,'sub',{value:id},`small ${sub===id?'primary':''}`)).join('')}</div>`+
(sub==='craft'?D.recipes.map(r=>`<div class="item-row">${img(r.slot)}<div><strong>${r.name}</strong><p>T${r.tier} · 鍛造舖 Lv.${r.unlock}</p>${cost(r.cost)}</div>${button('鍛造','craft',{recipeId:r.id},'small',state.buildings.forge<r.unlock)}</div>`).join(''):
sub==='gems'?section('背包寶石',state.gems.map(gm=>`<div class="item-row">${img(gm.type)}<div><strong>${esc(D.gemTypes[gm.type]?.name||gm.type)} Lv.${gm.tier}</strong><p>選擇裝備插槽可鑲嵌。</p></div>${button('合成','fuseGem',{type:gm.type,tier:gm.tier},'small')}</div>`).join('')||'<p class="empty-note">狩獵、挑戰與商店都能獲得寶石。三顆同種同級可合成。</p>'):
`<div class="row between"><span class="small muted">${state.inventory.length} / ${cap.inventory} 件</span><select data-change="inventoryFilter" aria-label="裝備分類"><option value="all">全部部位</option>${D.slots.map(sl=>`<option value="${sl.id}" ${inventoryFilter===sl.id?'selected':''}>${sl.name}</option>`).join('')}</select></div><div class="equipment-grid" style="margin-top:14px">${items.map(i=>`<button class="item-tile rarity-${i.stars}" data-item="${i.id}"><span class="enhance">+${i.enhance}</span>${img(i.slot)}<strong>${esc(i.name)}</strong><small>T${i.tier} ${'★'.repeat(i.stars)}${equippedBy(i.id)?' · 已穿戴':i.locked?' · 鎖定':''}</small></button>`).join('')}</div>${!items.length?'<p class="empty-note">第一件戰利品正在前方等待你。派出獵隊開始狩獵。</p>':''}${uiButton('批次分解','dismantleBatch',{},'ghost')}<label class="settings-row">自動分解掉落<select data-change="autoDismantle">${[0,1,2,3,4].map(n=>`<option value="${n}" ${state.settings.autoDismantle===n?'selected':''}>${n?'≤ '+n+' 星':'關閉'}</option>`).join('')}</select></label>`)+
section('素材倉庫',`<div class="material-list">${Object.entries(D.materials).map(([id,name])=>`<div class="material">${img(id)}<span>${name}<strong>${fmt(state.materials[id])}</strong></span></div>`).join('')}</div>`);}
function renderItem(it){const owner=equippedBy(it.id),s=C.itemStats(it),sl=D.slots.find(sl=>sl.id===it.slot);return uiButton('← 裝備倉庫','inventory',{},'ghost')+heading(it.name,`T${it.tier} · ${sl.name} · ${'★'.repeat(it.stars)}${it.classId?' · '+D.classes[it.classId].name+'專用':''}`)+`<div class="building-detail-illustration">${img(it.slot)}</div>`+
feature('強化等級','+'+it.enhance+' / 15')+feature('穿戴者',owner?.name||'尚未穿戴')+Object.entries(s).filter(([,v])=>typeof v==='number'&&v).map(([k,v])=>feature(({attack:'攻擊',defense:'防禦',maxHp:'生命',maxMp:'魔力',speed:'攻速',crit:'暴擊',hp:'生命',mp:'魔力'})[k]||k,['crit','speed'].includes(k)?fmt(v*100)+'%':fmt(v))).join('')+
(it.set?feature('套裝',D.sets[it.set].name):'')+(it.affix?feature('詞綴',D.affixes[it.affix.id||it.affix]?.name||JSON.stringify(it.affix)):'')+
section('鍛造強化',cost(C.enhanceCost(state,it))+`<div class="button-row">${button('強化 +1','enhance',{itemId:it.id},'primary',it.enhance>=15)}${button('強化 5 次','enhance',{itemId:it.id,count:5},'',it.enhance>=15)}</div>${button('重鑄詞綴','reroll',{itemId:it.id},'ghost')}`)+
section('寶石插槽',it.gems.map((gm,index)=>`<div class="row between"><span class="small">${gm?`${D.gemTypes[gm.type].name} Lv.${gm.tier}`:'空插槽 '+(index+1)}</span>${gm?button('拆卸','unsocket',{itemId:it.id,index},'small'):uiButton('鑲嵌寶石','socket',{itemId:it.id,index},'small')}</div>`).join('')||'<p class="empty-note">此裝備沒有寶石插槽。</p>')+
section('裝備管理',`<label class="field small">選擇穿戴者<select id="equip-hero">${state.heroes.filter(h=>!it.classId||h.classId===it.classId).map(h=>`<option value="${h.id}">${esc(h.name)} Lv.${h.level}</option>`).join('')}</select></label><div class="button-row" style="margin-top:10px">${uiButton('穿戴','equip',{itemId:it.id},'primary')}${owner?button('卸下','unequip',{heroId:owner.id,slot:it.slot}):''}${button(it.locked?'解鎖':'鎖定','lockItem',{itemId:it.id})}</div>${uiButton('分解裝備','dismantle',{itemIds:[it.id]},'danger wide',it.locked||!!owner)}`);}
function actionRow(row,label){return `<div class="challenge-card"><div class="row between"><h3>${esc(row.name)}</h3>${row.level!==undefined?`<span class="pill">Lv.${row.level}${row.max?' / '+row.max:''}</span>`:''}</div>${row.description?`<p>${esc(row.description)}</p>`:''}${row.remaining!==undefined&&row.remaining!==null?`<p>剩餘 ${row.remaining} 次</p>`:''}${row.opponentPower?feature('對手戰力',fmt(row.opponentPower)):''}${reward(row.reward)}${Object.keys(row.cost||{}).length?cost(row.cost):''}${row.reason?`<p>${esc(row.reason)}</p>`:''}${button(label||row.label||'執行',row.type||row.action,row.payload||{},'small',row.locked)}</div>`;}
function taskRow(t){return `<div class="task-card ${t.claimed?'complete':''}"><div class="caption"><h3>${esc(t.name)}</h3><span class="small muted">${fmt(Math.min(t.progress,t.target))} / ${fmt(t.target)}</span></div>${t.description?`<p>${esc(t.description)}</p>`:''}${bar(t.progress,t.target)}${reward(t.reward)}<div class="row between"><span class="small muted">${esc(t.bonus||'')}</span>${button(t.claimed?'已領取':'領取',t.type||t.action||'quest',t.payload||{kind:t.group,id:t.id},`small ${t.ready&&!t.claimed?'gold':''}`,t.locked??(!t.ready||t.claimed))}</div></div>`;}
function renderQuests(){const v=extView();return heading('公會委託簿','完成目標，逐步擴建你的獵人王國。','THE JOURNAL')+
`<div class="button-row">${v.signin?button(v.signin.locked?'今日已簽到':'每日簽到',v.signin.type,v.signin.payload,'gold',v.signin.locked):''}${v.chest?button(v.chest.locked?'寶箱已領取':'開啟每日寶箱',v.chest.type,v.chest.payload,'',v.chest.locked):''}</div>`+
`<div class="tabs">${[['main','主線'],['daily','每日'],['weekly','每週'],['achievement','成就'],['tutorial','教學'],['milestone','里程碑']].map(([id,name])=>uiButton(name,'questGroup',{id},`small ${questGroup===id?'primary':''}`)).join('')}</div>`+
button('領取所有已完成獎勵','claimAll',{},'wide small')+
(questGroup==='milestone'?(v.milestones||[]):(v.tasks||[]).filter(t=>t.group===questGroup)).map(taskRow).join('')+
section('回歸禮物',(v.returnGift||[]).map(taskRow).join(''))+
`<p class="subline">每日與每週進度依存檔的日期結算。重複點擊不會重複領取。</p>`;}
function renderShop(){const v=extView();return heading('城堡市集','整裝、補給，再踏上下一段旅途。','THE MARKET')+
section('隨身藥水',Object.entries(state.consumables).filter(([k])=>['hp','mp','attack','gold','xp','hourglass','goldBag'].includes(k)).map(([kind,n])=>`<div class="item-row">${img(kind)}<div><strong>${names[kind]||kind}</strong><p>持有 ${fmt(n)}</p></div>${button('使用','potion',{kind},'small',!n)}</div>`).join(''))+
section('市集貨架',(v.shops||[]).map(r=>actionRow(r,'購買')).join(''))+section('活動',`<p class="subline">${esc(v.event?.name||'狩獵祭')} · 累積 ${fmt(v.event?.earned||0)} 點</p>`);}
function renderChallenges(){const v=extView(),last=v.lastChallenge;return heading('冒險試煉','以隊伍戰力與職業配置挑戰秘境。每種試煉有獨立進度與次數。','BEYOND THE WALLS')+
(last?`<div class="goal-box"><h3>${last.success===false?'本次挑戰失利':'最近一次挑戰'}</h3><p>${esc(last.message||last.name||last.kind||'挑戰已結算')}</p>${reward(last.reward)}</div>`:'')+
(v.challenges||[]).map(r=>`<div class="challenge-card"><div class="row between"><h3>${esc(r.name)}</h3><span class="pill ${r.locked?'lock':''}">${r.remaining===null?'無次數限制':r.remaining+' 次剩餘'}</span></div><p>${esc(r.description)}</p>${feature('對手戰力',fmt(r.opponentPower))}${r.chance!==undefined?feature('目前預估勝率',fmt(r.chance*100)+'%'):''}${reward(r.reward)}${r.reason?`<p>${esc(r.reason)}</p>`:''}${uiButton('查看挑戰','challenge',{row:r},'small',r.locked)}</div>`).join('')+
section('競技場',feature('目前排名','第 '+(v.arena?.rank||10)+' 名')+`<select id="arena-target" aria-label="選擇競技場對手">${(v.arena?.opponents||[]).map(o=>`<option value="${o.rank}">#${o.rank} ${esc(o.name)} · ${fmt(o.power)}</option>`).join('')}</select>${uiButton('挑戰對手','arena',{},'wide')}${button('設為防守隊伍','arenaDefense',{team:state.selectedTeam},'ghost wide')}`)+
section('迷宮祝福',(v.labyrinth?.choices||[]).map(r=>actionRow(r,'選擇祝福')).join('')||`<p class="subline">探索進度 ${v.labyrinth?.node||0} / 12。部分節點提供永久保留至本週結束的祝福。</p>`)+
section('深淵模式',button('切換至深淵','target',{zone:state.hunting.zone,stage:state.hunting.stage,mode:'abyss'},'wide')+button('返回主線','target',{zone:state.hunting.zone,stage:state.hunting.stage,mode:'main'},'ghost wide'));
}
function renderWanderers(){const v=extView();return heading('城堡裡的過客','旅人會自行在城堡活動、短程狩獵與休息。餵食建立好感，或招募他們加入公會。','PASSING TRAVELERS')+
((v.wanderers||[]).map(w=>`<div class="challenge-card"><div class="hero-portrait">${img(w.classId||'knight')}<div><h3>${esc(w.name)}</h3><div class="stars">${'★'.repeat(w.stars||1)}</div><p>Lv.${w.level} · ${esc(w.statusLabel||w.status||'休息中')}</p></div></div>${feature('心情',fmt(w.mood))}${feature('生命',fmt(w.hp)+' / '+fmt(w.maxHp))}${w.actions?w.actions.map(r=>actionRow(r,r.name)).join(''):`<div class="button-row">${button('餵食','wanderer',{id:w.id,action:'feed'},'small')}${button('招募','wanderer',{id:w.id,action:'recruit'},'small')}</div>`}${uiButton('安排遠征','visitorExpedition',{id:w.id},'ghost')}${w.status==='expedition'?button('取消遠征','wanderer',{id:w.id,action:'cancel'},'small'):''}</div>`).join('')||'<p class="empty-note">城門外傳來腳步聲。新的流浪獵人將隨時間抵達。</p>');}
function renderExpeditions(){const v=extView();return heading('遠征委託','選擇合適的獵人，換取素材與公會補給。遠征期間獵人無法參加狩獵。','THE EXPEDITIONS')+
section('派遣中的隊伍',(v.activeCommissions||[]).map(r=>`<div class="challenge-card"><h3>${esc(r.name||'遠征委託')}</h3><p>${duration(Math.max(0,(r.endAt-Date.now())/1000))} 後返回</p>${button('召回（放棄獎勵）','commissionRecall',{id:r.id},'small')}</div>`).join('')||'<p class="empty-note">目前沒有派遣中的隊伍。</p>')+
section('可接委託',(v.commissions||[]).map(r=>`<div class="challenge-card"><div class="row between"><h3>${esc(r.name)}</h3><span class="pill gold">${esc(r.quality)}</span></div><p>${r.hours} 小時 · 所需戰力 ${fmt(r.requiredPower)}</p>${reward(r.reward)}<p>${esc(r.reason||'可挑選未派遣的獵人')}</p>${uiButton(r.active?'派遣中':'選擇獵人','commission',{row:r},'small',r.locked||!!r.active)}</div>`).join(''));}
function renderGuild(){const guild=extView().guild;return heading('公會殿堂','共同的研究與累積，化為每一支獵隊的力量。','GUILD HALL')+`<div class="stat-grid">${stat('公會等級','Lv.'+guild.level)}${stat('公會經驗',fmt(guild.xp)+' / '+fmt(guild.xpRequired))}</div>`+bar(guild.xp,guild.xpRequired,'gold')+section('公會捐獻',guild.donations.map(r=>actionRow(r,'捐獻')).join(''))+section('公會科技',guild.technology.map(r=>actionRow(r,'研究')).join(''))+link('前往公會首領','challenges','wide');}
function renderArtifacts(){const v=extView();return heading('傳承之物','從首領與深淵收集神器，讓傳說力量陪伴你的獵人。','RELICS & LEGENDS')+(v.artifacts||[]).map(a=>`<div class="challenge-card"><div class="item-row">${img('artifacts')}<div><strong>${esc(a.name)}</strong><p>${esc(a.description)}</p><span class="pill ${a.owned?'gold':'lock'}">${a.owned?'精煉 '+a.level+' · 覺醒 '+a.awakening:'尚未取得'}</span></div></div>${a.owned?uiButton('裝備給獵人','artifactEquip',{id:a.id},'wide'):''}${(a.actions||[]).map(r=>actionRow(r,r.name)).join('')}</div>`).join('')+section('傳說徽章',(v.badges||[]).map(r=>actionRow(r,'升級徽章')).join(''));}
function renderCollections(){const v=extView();return heading('王國圖鑑','每次相遇、每件戰利品，都成為城堡收藏的一部分。','FIELD NOTES')+feature('收藏完成度',fmt(v.collectionPercent)+'%')+`<div class="tabs">${[['classes','職業'],['monsters','魔物'],['sets','套裝']].map(([id,name])=>uiButton(name,'sub',{value:id},`small ${sub===id?'primary':''}`)).join('')}</div>`+
(sub==='monsters'?D.zones.map(z=>section(z.name,[...z.monsters,z.boss].map(m=>feature(m.name,'擊敗 '+fmt(state.collections.monsters[m.id]||0)+' 次')).join(''))).join(''):sub==='sets'?Object.values(D.sets).map(s=>section(s.name+'套裝',s.personal.map(p=>feature(p.count+' 件效果',Object.entries(p.effects).map(([k,v])=>( {attack:'攻擊',hp:'生命',defense:'防禦',crit:'暴擊',speed:'攻速',reduction:'減傷',killHeal:'擊殺回血'}[k]||k)+' +'+Math.round(v*100)+'%').join(' · '))).join(''))).join(''):(v.collections||[]).map(taskRow).join(''));}
function renderResearch(){const v=extView(),a=C.ascensionInfo(state);return heading('學識與傳承','讓研究成為長久的力量，以飛升展開下一輪旅程。','LEGACY')+section('圖書館研習',(v.research||[]).map(r=>actionRow(r,'研究')).join(''))+section('榮譽強化',(v.honor||[]).map(r=>actionRow(r,'升級')).join(''))+section('王國飛升',feature('預計獲得',fmt(a.honor)+' 榮譽')+feature('永久加成',fmt((a.bonus||0)*100)+'% → '+fmt((a.nextBonus||0)*100)+'%')+`<p class="subline">${esc(a.reason)}</p>${uiButton('查看飛升重置項目','ascend',{},'gold wide',!a.eligible)}`)+section('王國傳統',Object.values(D.traditions).map(t=>`<div class="challenge-card"><h3>${t.name} · Lv.${state.traditions[t.id]||0}</h3><p>${esc(t.description)}</p>${button('選擇傳統','tradition',{id:t.id},'small',!state.traditionChoices)}</div>`).join(''));}
function renderResonance(){const r=extView().resonance;return heading('共鳴水晶','共鳴讓後備獵人跟上先行者的腳步；真實等級與養成投資仍分別保存。','RESONANCE')+feature('共鳴等級','Lv.'+r.base)+feature('槽位',r.capacity)+section('共鳴獵人',r.slots.map(sl=>`<label class="settings-row">槽位 ${sl.slot+1}<select data-change="resonance" data-slot="${sl.slot}"><option value="">空位</option>${state.heroes.filter(h=>!r.leaders.includes(h.id)).map(h=>`<option value="${h.id}" ${sl.heroId===h.id?'selected':''}>${esc(h.name)} Lv.${h.level}</option>`).join('')}</select></label>`).join(''))+section('先行者',r.leaders.map(id=>feature(state.heroes.find(h=>h.id===id)?.name||'', '基礎等級 '+(state.heroes.find(h=>h.id===id)?.level||1))).join(''));}
function renderSettings(){const s=world?.getStats();return heading('城堡設定','進度保存在這台瀏覽器。定期匯出存檔，可以把公會帶到其他裝置。','SETTINGS')+
section('存檔',`<p class="subline">${esc(saveProblem||'每五秒自動保存；離開頁面時也會保存。')}</p><div class="button-row">${uiButton('立即保存','save')}${uiButton('匯出存檔','export')}${uiButton('匯入存檔','import')}</div>${uiButton('匯出原始備份','backup',{},'ghost')}`)+
section('聲音與顯示',`<label class="settings-row">音效音量<input type="range" min="0" max="1" step="0.05" value="${prefs.sound}" data-pref="sound"></label><label class="settings-row">背景音樂<input type="range" min="0" max="1" step="0.05" value="${prefs.music}" data-pref="music"></label><label class="settings-row">減少動態<input type="checkbox" data-pref="reduced" ${prefs.reduced?'checked':''}></label><label class="settings-row">自動環繞<input type="checkbox" data-pref="orbit" ${prefs.orbit?'checked':''}></label><label class="settings-row">日夜光照<input type="range" min="0" max="24" step="0.25" value="${prefs.hour}" data-pref="hour"></label><label class="settings-row">日夜循環<input type="checkbox" data-pref="lightCycle" ${prefs.lightCycle?'checked':''}></label><label class="settings-row">城牆剖視<input type="checkbox" data-pref="cut" ${prefs.cut?'checked':''}></label>`)+
section('自動補給',`<label class="settings-row">自動喝藥<input type="checkbox" data-change="autoPotion" ${state.autoPotion.enabled?'checked':''}></label><label class="settings-row">生命觸發線<input type="range" data-change="hpThreshold" min="0.1" max="0.9" step="0.05" value="${state.autoPotion.hp}"></label><label class="settings-row">魔力觸發線<input type="range" data-change="mpThreshold" min="0.1" max="0.9" step="0.05" value="${state.autoPotion.mp}"></label>`)+
section('場景檢視',feature('城堡種子',state.worldSeed)+feature('生成版本',state.generationVersion)+feature('體素數',fmt(s?.blocks))+feature('繪製呼叫',fmt(s?.drawCalls))+feature('幾何體 / 貼圖',`${s?.geometries||0} / ${s?.textures||0}`)+`<div class="button-row">${uiButton('防線俯視','camera',{name:'top'})}${uiButton('庭院近看','camera',{name:'courtyard'})}</div><p class="subline">場景使用獨立種子與實例化。鏡頭、光照與檢視不消耗遊戲亂數。</p>`)+
section('重新開始',`<p class="subline">建立新公會會替換目前存檔。請先匯出要保留的進度。</p>${uiButton('建立新公會','newGame',{},'danger wide')}`);}
function chooser(title,options,callback,description=''){confirm(title,`<p>${esc(description)}</p><select id="dialog-choice" style="width:100%">${options.map(o=>`<option value="${esc(o.id)}">${esc(o.name)}</option>`).join('')}</select>`,()=>{const value=$('#dialog-choice').value;if(value)callback(value);else toast('沒有可選對象',false);});}
function checkPicker(title,items,callback,description=''){confirm(title,`<p>${esc(description)}</p><div class="checkbox-list">${items.map(h=>`<label class="hero-checkbox"><input type="checkbox" value="${esc(h.id)}">${esc(h.name)}</label>`).join('')||'<p>目前沒有符合條件的對象。</p>'}</div>`,el=>callback([...el.querySelectorAll('input:checked')].map(i=>i.value)));}
function doUI(action,p={}){const hero=state.heroes.find(h=>h.id===p.heroId);
switch(action){
case'depart':{const result=act('dispatch');if(result.ok)go('hunt');break;}
case'formation':go('heroes');setTimeout(()=>$('#panel').scrollTo({top:$('#panel').scrollHeight,behavior:prefs.reduced?'instant':'smooth'}),0);break;
case'roster':selectedHero=null;page='heroes';dirty=true;render(true);break;
case'inventory':selectedItem=null;page='equipment';dirty=true;render(true);break;
case'sub':sub=p.value;render(true);break;
case'questGroup':questGroup=p.id;render(true);break;
case'focus':worldView='castle';world?.setView('castle');world?.focus(p.id);break;
case'camera':world?.setCamera(p.name);break;
case'map':worldView=worldView==='map'?(page==='hunt'?'battle':'castle'):'map';world?.setView(worldView);renderHUD();break;
case'wishlist':checkPicker('心願職業',D.classList.map(c=>({id:c.id,name:c.name})),classes=>act('wishlist',{classes}),'最多選兩種職業；所選職業的相對權重加倍，不改變招募星級機率。');break;
case'rename':if(hero)confirm('更改獵人名字',`<p>目前姓名：${esc(hero.name)}</p><input id="rename-input" maxlength="24" value="${esc(hero.name)}" aria-label="新名字">`,()=>act('renameHero',{heroId:hero.id,name:$('#rename-input').value}));break;
case'synth':{const stars=Number($('#synth-stars').value),classId=$('#synth-class').value;confirm('合成獵人',`<p>製作 ${stars}★ ${D.classes[classId].name}</p>${cost({fragments:stars===4?30:60})}`,()=>act('synthHero',{classId,stars}));break;}
case'starUp':if(hero){const same=[1,2,3,4,6][hero.stars-1]||0,any=[0,1,1,2,2][hero.stars-1]||0;checkPicker(`${hero.name} · 升至 ${hero.stars+1}★`,state.heroes.filter(h=>h.id!==hero.id&&h.stars===hero.stars&&!h.locked&&!C.occupied(state,h)).map(h=>({id:h.id,name:`${h.name} · ${D.classes[h.classId].name} · Lv.${h.level}`})),materialIds=>{const chosen=materialIds.map(id=>state.heroes.find(h=>h.id===id));confirm('確認消耗獵人',`<p>將永久消耗以下 ${chosen.length} 位素材獵人。裝備卸回倉庫。</p><div class="dialog-detail">${chosen.map(h=>esc(h.name)+' · '+D.classes[h.classId].name+' · Lv.'+h.level).join('<br>')}</div>`,()=>act('starUp',{heroId:hero.id,materialIds,confirm:true}));},`需要 ${same} 位同職業與 ${any} 位任意職業的同星獵人。`);}break;
case'resetHero':if(hero)confirm('重置 '+hero.name,`<p>等級、突破與技能回到初始值；星級、裝備與神器保留。退還實際投入：</p>${reward(hero.investment)}`,()=>act('resetHero',{heroId:hero.id,confirm:true}));break;
case'dismiss':if(hero)confirm('解僱 '+hero.name,`<p>這位 ${hero.stars}★ Lv.${hero.level} 獵人將離開公會，無法復原。裝備會卸回倉庫。</p>`,()=>{const r=act('dismiss',{heroId:hero.id,confirm:true});if(r.ok){selectedHero=null;render(true);}});break;
case'swapHero':if(hero)chooser('選擇置換對象',state.heroes.filter(h=>h.id!==hero.id&&h.classId===hero.classId&&!h.locked&&!C.occupied(state,h)).map(h=>({id:h.id,name:h.name+' · '+h.stars+'★ Lv.'+h.level})),otherId=>{const other=state.heroes.find(h=>h.id===otherId);confirm('交換養成',`<p>${esc(hero.name)}（${hero.stars}★ Lv.${hero.level}）與 ${esc(other.name)}（${other.stars}★ Lv.${other.level}）交換星級、等級、突破、技能與投入。身份及裝備歸屬保留。</p>${cost({swapStones:1+Math.ceil(Math.abs(hero.stars-other.stars)/2)})}`,()=>act('swapHero',{heroId:hero.id,otherId,confirm:true}));});break;
case'equipPicker':{const h=hero||state.heroes[0];chooser('為 '+h.name+' 選擇裝備',state.inventory.filter(i=>(!p.slot||i.slot===p.slot)&&(!i.classId||i.classId===h.classId)).map(i=>({id:i.id,name:itemName(i)+(equippedBy(i.id)?' · '+equippedBy(i.id).name+'持有':'')})),itemId=>act('equip',{heroId:h.id,itemId}),'穿戴後，原部位裝備會留在倉庫。');break;}
case'equip':act('equip',{itemId:p.itemId,heroId:$('#equip-hero').value});break;
case'dismantleBatch':checkPicker('選擇要分解的裝備',state.inventory.filter(i=>!i.locked&&!equippedBy(i.id)&&!i.gems.some(Boolean)).map(i=>({id:i.id,name:itemName(i)})),itemIds=>doUI('dismantle',{itemIds}),'只列出未鎖定、未穿戴且沒有鑲嵌寶石的裝備。最多一次 100 件。');break;
case'dismantle':{const items=p.itemIds.map(id=>state.inventory.find(i=>i.id===id)).filter(Boolean);confirm('分解 '+items.length+' 件裝備',`<p>以下裝備將永久消失。有鑲嵌寶石的裝備須先拆卸寶石。</p><div class="dialog-detail">${items.map(i=>esc(itemName(i))+'<br>'+reward(C.dismantleReward(i))).join('<br>')}</div>`,()=>{const r=act('dismantle',{itemIds:p.itemIds,confirm:true});if(r.ok){selectedItem=null;render(true);}});break;}
case'socket':chooser('選擇寶石',state.gems.map(gm=>({id:gm.id,name:D.gemTypes[gm.type].name+' Lv.'+gm.tier})),gemId=>act('socket',{...p,gemId}));break;
case'challenge':{const r=p.row;confirm(r.name,`<p>${esc(r.description)}</p>${feature('己方戰力',fmt(C.teamPower(state)))}${feature('對手戰力',fmt(r.opponentPower))}${r.chance!==undefined?feature('預估成功率',fmt(r.chance*100)+'%'):''}${reward(r.reward)}<p>確認後消耗一次挑戰並立即結算結果。</p>`,()=>act(r.type,r.payload));break;}
case'arena':act('challenge',{kind:'arena',target:Number($('#arena-target').value)});break;
case'visitorExpedition':chooser('選擇遠征時間',[{id:'1',name:'1 小時'},{id:'4',name:'4 小時'},{id:'8',name:'8 小時'}],hours=>act('wanderer',{id:p.id,action:'expedition',hours:Number(hours),zone:state.progress.zone}),'遠征會持續真實時間，可離線等待返程。');break;
case'commission':checkPicker(p.row.name,state.heroes.filter(h=>!C.occupied(state,h)).map(h=>({id:h.id,name:`${h.name} · 戰力 ${fmt(C.heroStats(state,h).power)}`})),heroIds=>act('commission',{id:p.row.id,heroIds}),`${p.row.hours} 小時 · 所需戰力 ${fmt(p.row.requiredPower)}。只有閒置獵人可派遣。`);break;
case'artifactEquip':chooser('選擇神器持有人',state.heroes.map(h=>({id:h.id,name:h.name})),heroId=>act('artifact',{id:p.id,action:'equip',heroId}));break;
case'ascend':confirm('王國飛升',`<p><strong>失去：</strong>本輪所有獵人與養成、裝備、一般寶石、金幣、素材、消耗品、王國等級、建築與當輪關卡。遠征先依完成／召回規則結算。</p><p><strong>保留：</strong>寶石貨幣、榮譽、券、技能書、碎片、神器與徽章養成、公會科技、研究、傳統、永久圖鑑與首通、已領獎及日週限額。</p><p><strong>獲得：</strong>${fmt(C.ascensionInfo(state).honor)} 榮譽、一次傳統選擇、300 金幣與一位 2★ Lv.1 新獵人。本輪 ${state.heroes.length} 位獵人及 ${state.inventory.length} 件裝備將被重置。</p><p>可先取消並匯出存檔。确认飛升後將回到第一區。</p>`,()=>{const r=act('ascend',{confirm:true});if(r.ok){selectedHero=null;selectedItem=null;go('castle');}});break;
case'save':toast(save()?'進度已保存':'無法寫入儲存空間；請先匯出存檔',!saveProblem);break;
case'export':download(JSON.stringify(state,null,2),'蒼嵐堡-存檔-'+new Date().toISOString().slice(0,10)+'.json');break;
case'backup':{const raw=localStorage.getItem(saveKey);if(raw)download(raw,'蒼嵐堡-原始備份.json');else toast('沒有原始備份',false);break;}
case'import':$('#import-file').click();break;
case'newGame':confirm('建立新公會',`<p>目前公會將被替換。請先匯出存檔。輸入「重新開始」以確認。</p><input id="new-confirm" aria-label="輸入重新開始">`,()=>{if($('#new-confirm').value!=='重新開始'){toast('確認文字不符，存檔未更動',false);return;}state=C.create();saveProblem='';selectedHero=null;selectedItem=null;save();syncWorld();go('castle');toast('新公會已建立');});break;
}}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',event=>{const el=event.target.closest('button');if(!el||el.disabled)return;const p=el.dataset.payload?JSON.parse(el.dataset.payload):{};
if(el.dataset.nav){go(el.dataset.nav);return;}
if(el.dataset.hero){selectedHero=el.dataset.hero;page='heroes';render(true);return;}
if(el.dataset.item){selectedItem=el.dataset.item;page='equipment';render(true);return;}
if(el.dataset.zone){const id=el.dataset.zone;selectedWorld({kind:id==='abyss'?'abyss':'zone',id});return;}
if(el.dataset.building){selectedBuilding=el.dataset.building;page='building';worldView='castle';world?.setView('castle');world?.focus(selectedBuilding);render(true);return;}
if(el.dataset.action){act(el.dataset.action,p);return;}
if(el.dataset.ui){doUI(el.dataset.ui,p);return;}
if(el.dataset.camera){world?.setCamera(el.dataset.camera);return;}
if(el.dataset.world){switch(el.dataset.world){case'zoom-in':world?.zoom(.82);break;case'zoom-out':world?.zoom(1.22);break;case'inspect':inspect=!inspect;world?.setInspection(inspect);el.setAttribute('aria-pressed',inspect);break;case'cut':prefs.cut=!prefs.cut;world?.setCutaway(prefs.cut);el.setAttribute('aria-pressed',prefs.cut);save();break;case'map':doUI('map');el.setAttribute('aria-pressed',worldView==='map');break;}renderHUD();}
});
document.addEventListener('change',event=>{const el=event.target,d=el.dataset,n=Number(el.value);
if(d.pref){prefs[d.pref]=el.type==='checkbox'?el.checked:n;applyPrefs();save();renderHUD();return;}
switch(d.change){
case'zone':act('target',{zone:n,stage:1});break;case'stage':act('target',{zone:state.hunting.zone,stage:n});break;
case'autoNext':case'autoContinue':act(d.change,{value:el.checked});break;
case'autoPotion':act('autoPotion',{...state.autoPotion,enabled:el.checked});break;
case'hpThreshold':act('autoPotion',{...state.autoPotion,hp:n});break;case'mpThreshold':act('autoPotion',{...state.autoPotion,mp:n});break;
case'assign':act('assign',{heroId:el.value||null,team:state.selectedTeam,slot:Number(d.slot)});break;
case'skillSlot':{const h=state.heroes.find(h=>h.id===d.hero);act('selectSkill',{heroId:h.id,main:d.slot==='main'?n:h.mainSkill,sub:d.slot==='sub'?n:h.subSkill});break;}
case'inventoryFilter':inventoryFilter=el.value;render(true);break;case'autoDismantle':act('autoDismantle',{stars:n});break;
case'resonance':act('resonance',{slot:Number(d.slot),heroId:el.value||null});break;
}});
$('#save-indicator').addEventListener('click',()=>doUI('save'));
$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>8e6){toast('存檔超過 8 MB，無法載入',false);return;}try{const candidate=JSON.parse(await file.text()),v=C.migrate(candidate);if(!v.ok)throw Error(v.message);confirm('匯入存檔',`<p>將替換目前進度為王國 Lv.${candidate.kingdom.level}、${candidate.heroes.length} 位獵人的公會。</p>`,()=>{try{localStorage.setItem(saveKey+'-backup',JSON.stringify(state));state=candidate;E.init(state);const off=C.offline(state,Date.now());saveProblem='';save();syncWorld();go('castle');toast('存檔已匯入'+(off.seconds?'，已結算離線時間':''));}catch(error){toast(error.message,false);}});}catch(error){toast('存檔無效，現有進度未變：'+error.message,false);}});
let nextMusic=0;
/* Browsers only allow audio after a user gesture, so never open an AudioContext before one.
   (Opening one early also throws audio-device errors on machines with no output device.) */
function unlockAudio(){try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();}catch(_){} }
['pointerdown','keydown','touchstart'].forEach(type=>document.addEventListener(type,unlockAudio,{once:true,passive:true}));
function ambient(now){if(!audioContext||audioContext.state!=='running'||!prefs.music||document.hidden||now<nextMusic)return;nextMusic=now+6500;try{[130.81,196,261.63,329.63].forEach((freq,i)=>{const osc=audioContext.createOscillator(),gain=audioContext.createGain(),at=audioContext.currentTime+i*.6;osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(0,at);gain.gain.linearRampToValueAtTime(Number(prefs.music)*.025,at+.8);gain.gain.exponentialRampToValueAtTime(.0001,at+5);osc.connect(gain).connect(audioContext.destination);osc.start(at);osc.stop(at+5.1);});}catch(_){} }
function applyPrefs(){document.body.classList.toggle('reduce-motion',!!prefs.reduced);world?.setHour(Number(prefs.hour));world?.setCutaway(!!prefs.cut);world?.setOrbit(!!prefs.orbit&&!prefs.reduced);if(prefs.music&&audioContext){try{audioContext.resume();}catch(_){}}}
function selectedWorld(item){if(item.kind==='building'){page='building';selectedBuilding=item.id;}else if(item.kind==='hero'){if(item.visitor)page='wanderers';else {page='heroes';selectedHero=item.id;}}else if(item.kind==='zone'){if(Number(item.id)>state.progress.maxZone){toast('需先通過前一區首領',false);return;}act('target',{zone:Number(item.id),stage:1});go('hunt');return;}else if(item.kind==='abyss'){page='challenges';}else if(item.kind==='challenge'){const routes={commission:'expeditions',guild:'guild',quests:'quests',collections:'collections'};page=routes[item.id]||'challenges';}render(true);}
try{world=g.GameWorld.create({canvas:$('#world'),onSelect:selectedWorld,onError:message=>{const el=$('#world-message');el.hidden=false;el.textContent='3D 場景無法啟動：'+message+'。仍可透過選單進行遊戲。';}});syncWorld();applyPrefs();$('#world-message').hidden=true;}catch(error){console.error(error);$('#world-message').textContent='3D 場景未能啟動。可以繼續使用右側選單。';}
document.querySelectorAll('[data-icon]').forEach(el=>{el.src=I.icon(el.dataset.icon);});
let lastTime=performance.now(),lastReal=Date.now();
function frame(now){if(destroyed)return;const real=Date.now(),elapsed=Math.max(0,(real-lastReal)/1000);lastReal=real;
if(!document.hidden){if(elapsed>90){const report=C.offline(state,real);if(report?.seconds)toast('歡迎回來，離線收穫已結算。');}else if(elapsed>0)C.tick(state,elapsed,real);
if(prefs.lightCycle&&!prefs.reduced){prefs.hour=(Number(prefs.hour)+Math.min(elapsed,1)/25)%24;world?.setHour(prefs.hour);}
if(now-lastWorld>160){syncWorld();lastWorld=now;}
if(now-lastHud>350){render();lastHud=now;}
if(now-lastSave>5000){save();lastSave=now;}ambient(now);}
lastTime=now;raf=requestAnimationFrame(frame);}
document.addEventListener('visibilitychange',()=>{if(document.hidden){save();audioContext?.suspend();}else{const seconds=(Date.now()-state.lastSeen)/1000;if(seconds>2){const summary=C.offline(state,Date.now());if(seconds>90)toast('歡迎回來！已結算 '+duration(seconds)+' 的離線進度。');save();dirty=true;}lastReal=Date.now();if(prefs.music)audioContext?.resume();}});
window.addEventListener('pagehide',()=>save());
render(true);raf=requestAnimationFrame(frame);
if(saveProblem)toast(saveProblem,false);else if(offlineSummary?.seconds>90)toast('歡迎回來！離線收穫已入帳。');
g.GameApp={snapshot:()=>JSON.parse(JSON.stringify(state)),getWorldStats:()=>world?.getStats(),navigate:go,dispose(){destroyed=true;cancelAnimationFrame(raf);world?.dispose();audioContext?.close();}};
if(new URLSearchParams(location.search).has('test'))Object.assign(g.GameApp,{dispatch:act,replaceState(next){const v=C.validate(next);if(!v.ok)throw Error(v.message);state=structuredClone(next);E.init(state);syncWorld();render(true);},advance(seconds){C.tick(state,seconds,state.lastSeen+seconds*1000);syncWorld();render(true);},world:()=>world});
})(globalThis);
