'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const C=require('../js/game-core.js');
const D=require('../js/game-data.js');
const W=require('../js/world-map.js');
const epoch=Date.parse('2026-09-16T12:00:00+08:00');
function fresh(seed=74321){delete global.GameExtensions;const s=C.create(seed);s.createdAt=s.lastSeen=s.clock=epoch;s.events=[];return s;}
function act(s,t,p={}){return C.dispatch(s,t,p,s.clock);}
function cash(s){s.resources.gold=1e12;s.resources.gems=1e6;s.resources.tickets=1000;s.resources.books=10000;s.resources.fragments=1000;s.resources.swapStones=100;for(const k of Object.keys(s.materials))s.materials[k]=10000;s.buildings.tavern=30;s.buildings.forge=10;s.buildings.training=10;s.buildings.gem=10;}
function add(s,cls='swordsman',stars=2,level=1){const h=C.makeHero(s,cls,stars,level);s.heroes.push(h);return h;}
function unchanged(s,t,p){const before=JSON.stringify(s);const r=act(s,t,p);assert.equal(r.ok,false,r.message);assert.equal(JSON.stringify(s),before,'failed transaction must preserve resources, RNG and full state');}
function hunt(s,seconds){C.tick(s,seconds,s.clock+seconds*1000);}
/* Combat maths now only happens once the party has walked into reach, so these
   fixtures place the party on its melee ring instead of paying for the march. */
function engage(s){const f=s.hunting.field;if(!f)return;const slots=D.zones[s.hunting.zone-1].field.slots;for(const m of f.party){const w=D.ring.toWorld(s.hunting.zone-1,slots[m.slot%slots.length][0],slots[m.slot%slots.length][1]);m.x=w[0];m.z=w[1];m.path=[];m.pi=0;}f.phase='fight';}
/* A full five-hero party ordered out to one zone, with an enemy that cannot die. */
function marchSetup(zone){const s=fresh(11);s.progress.zone=s.progress.maxZone=zone;s.progress.stage=10;s.hunting.zone=zone;s.buildings.tavern=10;for(const cls of['mage','priest','swordsman','archer','knight'])add(s,cls);assert.equal(act(s,'autoTeam').ok,true);assert.equal(act(s,'dispatch').ok,true);s.hunting.enemy.attack=0;s.hunting.enemy.hp=s.hunting.enemy.maxHp=1e9;return s;}
/* Walk one dispatch to the monster, watching every step the party takes. */
function march(s,limit=900){const r={gate:false,minGap:Infinity,offGround:0,inSolid:0,far:Infinity,done:-1,ticks:0,nearTicks:0,worstRun:0};
  let run=0;
  for(let t=0;t<limit;t++){hunt(s,.1);const f=s.hunting.field;if(!f)break;
    r.ticks++;
    for(const m of f.party){if(!W.walkable(m.x,m.z))r.offGround++;if(W.blocked(m.x,m.z))r.inSolid++;if(Math.hypot(m.x-W.castle.gate.x,m.z-W.castle.gate.z)<9)r.gate=true;}
    let gap=Infinity;
    for(let a=0;a<f.party.length;a++)for(let b=a+1;b<f.party.length;b++){
      const g=Math.hypot(f.party[a].x-f.party[b].x,f.party[a].z-f.party[b].z);
      if(g>1e-9)gap=Math.min(gap,g);
    }
    r.minGap=Math.min(r.minGap,gap);
    if(gap<1.2){r.nearTicks++;run++;r.worstRun=Math.max(r.worstRun,run);}else run=0;
    r.far=Math.max(...f.party.map(m=>Math.hypot(m.x-f.foe.x,m.z-f.foe.z)));
    if(f.phase==='fight'&&r.far<=6){r.done=t*.1;break;}}
  return r;}
test('party repaths after a new enemy appears beyond a completed route',()=>{const s=fresh();assert.equal(act(s,'dispatch').ok,true);const f=s.hunting.field,m=f.party[0],gate=D.ring.toWorld(0,0,-13);m.x=gate[0];m.z=gate[1];m.path=[];m.pi=0;f.phase='fight';f.foe.aggro=false;f.foe.path=[];f.foe.pi=0;const before=s.stats.kills;hunt(s,12);assert.ok(s.stats.kills>before,'the party should reach and defeat the next enemy');});
test('legacy map save keeps progress but discards obsolete routes',()=>{const s=fresh();assert.equal(act(s,'dispatch').ok,true);const old=JSON.parse(JSON.stringify(s));old.generationVersion=1;old.hunting.field.party[0].path=[[999,999]];const rng=old.rng,resources=JSON.stringify(old.resources),enemy=JSON.stringify(old.hunting.enemy);assert.equal(C.migrate(old).ok,true);assert.equal(old.generationVersion,2);assert.equal(old.hunting.field,null);assert.equal(old.rng,rng);assert.equal(JSON.stringify(old.resources),resources);assert.equal(JSON.stringify(old.hunting.enemy),enemy);assert.equal(C.validate(old).ok,true);hunt(old,1);assert.ok(old.hunting.field?.party[0].path.length>5);});
test('castle rings are really spaced apart in the built voxels, not just in the constants',()=>{const castle=require('../js/castle-geometry.js').buildCastle(314159);const K=W.castle.keep;const side=batch=>batch.filter(b=>Math.abs(b[2])<=10).map(b=>Math.abs(b[0]));const keepX=Math.max(...castle.batches.keep.map(b=>Math.abs(b[0])));const keepZ=[Math.min(...castle.batches.keep.map(b=>b[2])),Math.max(...castle.batches.keep.map(b=>b[2]))];const inner=side(castle.batches.inner),outer=side(castle.batches.outer);const innerIn=Math.min(...inner),innerOut=Math.max(...inner),outerIn=Math.min(...outer);assert.ok(keepX<=K.x+K.tower+.05,`主堡不得超出主張的佔地（x ${keepX} vs ${K.x+K.tower}）`);assert.ok(keepZ[0]>=K.zMin-K.tower-.05&&keepZ[1]<=K.zMax+K.tower+.05,`主堡不得超出主張的佔地（z ${keepZ}）`);assert.ok(innerIn-keepX>=26,`內牆到主堡只有 ${(innerIn-keepX).toFixed(1)} 格（門檻 26）`);assert.ok(outerIn-innerOut>=26,`外牆到內牆只有 ${(outerIn-innerOut).toFixed(1)} 格（門檻 26）`);assert.ok(W.findPath([0,32],[0,W.castle.junction[1]]).length>0,'城內出生點必須走得到城門大道');});
test('all ten zones are reached on walkable ground without crossing a wall',()=>{for(let zone=1;zone<=10;zone++){const s=fresh(7);s.progress.zone=s.progress.maxZone=zone;s.progress.stage=10;s.hunting.zone=zone;assert.equal(act(s,'dispatch').ok,true);s.hunting.enemy.attack=0;s.hunting.enemy.hp=s.hunting.enemy.maxHp=1e9;for(let t=0;t<30&&s.hunting.field?.phase!=='fight';t++){hunt(s,1);const m=s.hunting.field?.party[0];assert.ok(m&&W.walkable(m.x,m.z),`zone ${zone}: party stayed on the continent`);assert.ok(Number.isFinite(W.height(m.x,m.z)));}assert.equal(s.hunting.field?.phase,'fight',`zone ${zone}: party reaches arena`);}});
test('the marching party keeps its formation, walks out of the gate and never enters solid rock',()=>{for(let zone=1;zone<=10;zone++){const r=march(marchSetup(zone));assert.ok(r.gate,`zone ${zone}: the route leaves through the castle gate`);assert.equal(r.offGround,0,`zone ${zone}: every step stayed on walkable ground`);assert.equal(r.inSolid,0,`zone ${zone}: nobody walked inside solid rock`);/* 隊形目標 2.6 格；成員同時收攏到同一隻怪物時允許短暫靠近，但永遠不准疊在同一點。 */assert.ok(r.minGap>=.3,`zone ${zone}: members never stand on one point (closest ${r.minGap.toFixed(2)})`);assert.ok(r.nearTicks/r.ticks<=.05,`zone ${zone}: close approaches stay transient (${r.nearTicks}/${r.ticks} ticks)`);assert.ok(r.worstRun<=3,`zone ${zone}: never crowded together for longer than 3 ticks (${r.worstRun})`);}});
test('a member that used up its route walks over to the monster instead of standing idle',()=>{for(let zone=1;zone<=10;zone++){const r=march(marchSetup(zone));assert.ok(r.done>=0,`zone ${zone}: every member closed on the monster within ${6} units (farthest ${r.far.toFixed(2)})`);}});
test('recall traverses the zone gate and returns to the castle spawn',()=>{const s=fresh(4);assert.equal(act(s,'dispatch').ok,true);s.hunting.enemy.attack=0;s.hunting.enemy.hp=s.hunting.enemy.maxHp=1e9;hunt(s,14);assert.equal(act(s,'recall').ok,true);for(let t=0;t<25&&s.hunting.field;t++)hunt(s,1);assert.equal(s.hunting.field,null,'return route finishes');});
test('new game has exact starter resources/capacities and is serializable',()=>{const s=fresh();assert.equal(s.resources.gold,300);assert.equal(s.resources.gems,120);assert.equal(s.resources.tickets,1);assert.deepEqual(C.capacity(s),{roster:6,inventory:210,slots:2,teams:1});assert.equal(s.heroes.length,1);assert.equal(s.heroes[0].stars,2);assert.equal(s.hunting.active,false);assert.equal(C.validate(JSON.parse(JSON.stringify(s))).ok,true);});
test('world seed and inspection-independent calls never advance gameplay RNG',()=>{const a=fresh(42),b=fresh(42);a.worldSeed='new cosmetic layout';C.heroStats(a,a.heroes[0]);C.enemyPreview(a,1,10,0);C.teamPower(a);assert.equal(a.rng,b.rng);act(a,'recruit',{kind:'advanced'});act(b,'recruit',{kind:'advanced'});assert.deepEqual(a.heroes,b.heroes);});
test('invalid and unaffordable operations are atomic including RNG',()=>{const s=fresh();unchanged(s,'recruit',{kind:'mythic'});unchanged(s,'recruit',{kind:'normal',count:-2});unchanged(s,'wishlist',{classes:['mage','mage']});unchanged(s,'target',{zone:10,stage:10});unchanged(s,'nothing',{});});
test('normal recruitment exact cost, capacity and batch count',()=>{const s=fresh();assert.equal(C.recruitCost(s,'normal').gold,147);const r=act(s,'recruit',{kind:'normal',count:10});assert.equal(r.count,1);assert.equal(s.resources.gold,153);assert.equal(s.recruitment.normal,1);cash(s);s.buildings.tavern=1;const result=act(s,'recruit',{kind:'advanced',count:10});assert.equal(result.count,4);assert.equal(s.heroes.length,6);unchanged(s,'recruit',{kind:'advanced'});});
test('advanced tenth and mythic twentieth pity, early success reset',()=>{const s=fresh();cash(s);s.recruitment.advancedPity=9;assert.equal(act(s,'recruit',{kind:'advanced'}).ok,true);assert.equal(s.heroes.at(-1).stars,5);assert.equal(s.recruitment.advancedPity,0);s.recruitment.mythicPity=19;assert.equal(act(s,'recruit',{kind:'mythic'}).ok,true);assert.equal(s.heroes.at(-1).stars,6);assert.equal(s.recruitment.mythicPity,0);let found=false;for(let seed=1;seed<1000&&!found;seed++){const x=fresh(seed);x.recruitment.advancedPity=2;act(x,'recruit',{kind:'advanced'});if(x.heroes.at(-1).stars===5){assert.equal(x.recruitment.advancedPity,0);found=true;}}assert.ok(found);});
test('assign moves unique identity; busy heroes cannot be rearranged or consumed',()=>{const s=fresh();cash(s);const h=s.heroes[0];assert.equal(act(s,'assign',{heroId:h.id,team:1,slot:0}).ok,true);assert.equal(s.teams[0][0],null);act(s,'selectTeam',{index:1});act(s,'dispatch');unchanged(s,'assign',{heroId:h.id,team:0,slot:0});unchanged(s,'resetHero',{heroId:h.id,confirm:true});unchanged(s,'dismiss',{heroId:h.id,confirm:true});act(s,'recall');h.expeditionId='commission';unchanged(s,'assign',{heroId:h.id,team:0,slot:0});});
test('starter free route can recruit two, fight, progress, obtain XP and loot',()=>{const s=fresh(42);act(s,'recruit',{kind:'normal'});act(s,'autoTeam');act(s,'dispatch');hunt(s,120);assert.ok(s.stats.kills>0);assert.ok(s.progress.totalStages>0);assert.ok(s.heroes.some(h=>h.level>1));assert.ok(s.kingdom.level>=2);assert.ok(s.resources.gold>153);assert.equal(C.validate(s).ok,true);});
test('battle speed accelerates only fighting; rest remains twenty real seconds',()=>{const a=fresh(99),b=JSON.parse(JSON.stringify(a));act(a,'autoNext',{value:false});act(b,'autoNext',{value:false});act(b,'speed',{value:4});act(a,'dispatch');act(b,'dispatch');hunt(a,15);hunt(b,15);assert.ok(b.stats.kills>a.stats.kills);for(const speed of [1,2,4]){const s=fresh();s.hunting.speed=speed;s.hunting.restUntil=s.clock+20000;s.hunting.autoContinue=false;s.heroes[0].hp=0;hunt(s,19.9);assert.ok(s.hunting.restUntil>s.clock);assert.equal(s.heroes[0].hp,0);hunt(s,.1);assert.equal(s.hunting.restUntil,0);assert.equal(s.heroes[0].hp,C.heroStats(s,s.heroes[0]).maxHp);assert.equal(s.hunting.active,false);}});
test('recall never grants instant healing and idle healing uses real time',()=>{const s=fresh(),h=s.heroes[0];h.hp=10;act(s,'dispatch');act(s,'recall');assert.equal(h.hp,10);const max=C.heroStats(s,h).maxHp;hunt(s,1);assert.ok(Math.abs(h.hp-(10+max*.02))<1e-6);});
test('stat formulas, equipment gems, personal and team sets stack correctly',()=>{const s=fresh();cash(s);const h=add(s,'swordsman',4,25);h.breakthrough=2;const baseline=C.heroStats(s,h);assert.ok(Math.abs(baseline.attack-(12+3.2*24)*1.6*1.2**2)<1e-8);act(s,'assign',{heroId:h.id,team:1,slot:0});for(const slot of ['helmet','armor','boots','necklace']){const it=C.makeItem(s,8,{slot,stars:3,set:'wolf'});it.affix=null;s.inventory.push(it);act(s,'equip',{heroId:h.id,itemId:it.id});}const st=C.heroStats(s,h);assert.ok(st.attack>baseline.attack*1.13);assert.ok(st.crit>=baseline.crit+.12);const it=s.inventory[0];it.holes=1;it.gems=[null];const gm=C.makeGem(s,5,'red'),before=C.heroStats(s,h).attack;act(s,'socket',{itemId:it.id,gemId:gm.id,index:0});assert.ok(C.heroStats(s,h).attack>before);assert.equal(s.gems.length,0);act(s,'unsocket',{itemId:it.id,index:0});assert.equal(s.gems.length,1);assert.equal(C.heroStats(s,h).attack,before);});
test('training/reset returns only actual investments and skill books exactly once',()=>{const s=fresh();cash(s);const h=s.heroes[0],initial=s.resources.gold;act(s,'train',{heroId:h.id,count:3});const spent=initial-s.resources.gold;assert.ok(h.investment.gold>0);h.level=10;act(s,'breakthrough',{heroId:h.id});act(s,'skill',{heroId:h.id,index:0});const investment=structuredClone(h.investment),gold=s.resources.gold,books=s.resources.books,iron=s.materials.iron;assert.equal(act(s,'resetHero',{heroId:h.id,confirm:true}).ok,true);assert.equal(h.level,1);assert.equal(h.breakthrough,0);assert.equal(s.resources.gold,gold+investment.gold);assert.equal(s.resources.books,books+investment.books);assert.equal(s.materials.iron,iron+investment.materials.iron);const after=s.resources.gold;act(s,'resetHero',{heroId:h.id,confirm:true});assert.equal(s.resources.gold,after);assert.ok(spent<=investment.gold);});
test('star up validates exact materials and unloads consumed equipment',()=>{const s=fresh();cash(s);const h=add(s,'mage',2),m1=add(s,'mage',2),m2=add(s,'mage',2),m3=add(s,'archer',2),it=C.makeItem(s,3,{slot:'helmet'});s.inventory.push(it);act(s,'equip',{heroId:m1.id,itemId:it.id});unchanged(s,'starUp',{heroId:h.id,materialIds:[m1.id,m1.id,m3.id],confirm:true});assert.equal(act(s,'starUp',{heroId:h.id,materialIds:[m1.id,m2.id,m3.id],confirm:true}).ok,true);assert.equal(s.heroes.find(x=>x.id===h.id).stars,3);assert.equal(s.inventory.filter(x=>x.id===it.id).length,1);assert.equal(s.heroes.find(x=>x.id===m1.id),undefined);});
test('swap preserves identity/equipment/artifact, transfers exact investments',()=>{const s=fresh();cash(s);const a=add(s,'mage',2,10),b=add(s,'mage',5,70);a.legend='mona';a.artifact='dragon';a.investment.gold=1500;b.investment.gold=9000;const aid=a.id,bid=b.id;assert.equal(act(s,'swapHero',{heroId:aid,otherId:bid,confirm:true}).ok,true);assert.equal(a.level,70);assert.equal(b.level,10);assert.equal(a.legend,'mona');assert.equal(a.artifact,'dragon');assert.equal(a.id,aid);assert.equal(b.id,bid);assert.equal(a.investment.gold,9000);assert.equal(s.resources.swapStones,97);});
test('synthesis limits weekly 4/5 stars independently and requires resources',()=>{const s=fresh();cash(s);assert.equal(act(s,'synthHero',{classId:'priest',stars:4}).ok,true);assert.equal(act(s,'synthHero',{classId:'priest',stars:4}).ok,true);unchanged(s,'synthHero',{classId:'priest',stars:4});assert.equal(act(s,'synthHero',{classId:'priest',stars:5}).ok,true);unchanged(s,'synthHero',{classId:'priest',stars:5});s.clock+=7*86400000;assert.equal(act(s,'synthHero',{classId:'priest',stars:5}).ok,true);});
test('enhancement stops exactly +15; final surcharges are applied',()=>{const s=fresh();cash(s);const it=C.makeItem(s,10,{stars:6});s.inventory.push(it);it.enhance=13;const expected=Math.floor(Math.floor(40*10**1.6*1.5**13)*3*Math.max(.1,1-.04*s.buildings.forge));assert.equal(C.enhanceCost(s,it).gold,expected);assert.equal(act(s,'enhance',{itemId:it.id,count:100}).count,2);assert.equal(it.enhance,15);unchanged(s,'enhance',{itemId:it.id});});
test('gem replacement returns previous gem; fusion cannot consume equipped/top tier',()=>{const s=fresh();cash(s);const it=C.makeItem(s,5,{stars:5});s.inventory.push(it);const first=C.makeGem(s,1,'red'),second=C.makeGem(s,1,'blue');act(s,'socket',{itemId:it.id,gemId:first.id,index:0});act(s,'socket',{itemId:it.id,gemId:second.id,index:0});assert.ok(s.gems.some(g=>g.id===first.id));C.makeGem(s,1,'red');C.makeGem(s,1,'red');assert.equal(act(s,'fuseGem',{type:'red',tier:1}).ok,true);assert.ok(s.gems.some(g=>g.type==='red'&&g.tier===2));for(let i=0;i<3;i++)C.makeGem(s,10,'blue');unchanged(s,'fuseGem',{type:'blue',tier:10});});
test('dismantle refuses locked/equipped/socketed items and returns all tier materials',()=>{const s=fresh();cash(s);const it=C.makeItem(s,10,{stars:6,slot:'armor'});s.inventory.push(it);it.locked=true;unchanged(s,'dismantle',{itemIds:[it.id],confirm:true});it.locked=false;const gm=C.makeGem(s,1,'red');act(s,'socket',{itemId:it.id,gemId:gm.id,index:0});unchanged(s,'dismantle',{itemIds:[it.id],confirm:true});act(s,'unsocket',{itemId:it.id,index:0});const before=structuredClone(s.materials);assert.equal(act(s,'dismantle',{itemIds:[it.id],confirm:true}).ok,true);for(const k of Object.keys(D.materials))assert.ok(s.materials[k]>before[k]);});
test('full inventory keeps gold/material rewards and auto-dismantles eligible loot',()=>{const s=fresh();for(let n=0;n<210;n++)s.inventory.push(C.makeItem(s,1,{stars:1}));const gold=s.resources.gold;C.addReward(s,{gold:123,materials:{iron:5}});assert.equal(C.receiveItem(s,C.makeItem(s,3,{stars:4})),false);assert.equal(s.resources.gold,gold+123);assert.equal(s.materials.iron,5);s.settings.autoDismantle=1;assert.equal(C.receiveItem(s,C.makeItem(s,1,{stars:1})),true);assert.equal(s.inventory.length,210);assert.ok(s.materials.iron>5);});
test('boss/difficulty values multiply defense once, final region never becomes eleven',()=>{const s=fresh();const e=C.enemyPreview(s,1,10,3);assert.equal(e.defense,2*2.44);assert.equal(e.hp,Math.round(80*2.44*2.4*5.5));s.progress.zone=10;s.progress.stage=10;s.hunting.zone=10;s.hunting.stage=10;s.heroes[0].level=200;s.heroes[0].stars=6;s.heroes[0].breakthrough=5;act(s,'dispatch');engage(s);s.hunting.enemy.hp=1;hunt(s,2);assert.equal(s.progress.zone,10);assert.equal(s.hunting.zone,10);assert.equal(s.hunting.mode,'main');assert.ok(s.progress.firstClears.includes(10));});
test('permanent and daily boss rewards cannot be repeatedly earned',()=>{const s=fresh();cash(s);s.heroes[0].level=200;s.progress.stage=10;s.hunting.stage=10;s.hunting.autoNext=false;act(s,'dispatch');engage(s);let last=s.resources.gems;for(let i=0;i<2;i++){if(!s.hunting.enemy)hunt(s,.1);s.hunting.enemy.hp=1;hunt(s,1.5);const delta=s.resources.gems-last;assert.equal(delta,i===0?25:0);last=s.resources.gems;}assert.equal(s.stats.dailyBossKills,1);assert.deepEqual(s.progress.firstClears,[1]);});
test('potions heal only actual deployed team, can revive one, cannot skip full defeat',()=>{const s=fresh();cash(s);const a=s.heroes[0],b=add(s,'priest'),reserve=add(s,'mage');act(s,'assign',{heroId:b.id,team:0,slot:1});reserve.hp=1;s.consumables.hp=4;act(s,'dispatch');b.hp=0;a.hp=1;assert.equal(act(s,'potion',{kind:'hp'}).ok,true);assert.equal(b.hp,C.heroStats(s,b).maxHp*.5);assert.equal(reserve.hp,1);s.hunting.active=false;s.hunting.restUntil=s.clock+20000;unchanged(s,'potion',{kind:'hp'});});
test('offline idle gives no hunt income; active caps at 12h and settles once',()=>{const idle=fresh();const old=idle.resources.gold;assert.equal(C.offline(idle,epoch+86400000).gold,0);assert.equal(idle.resources.gold,old);const s=fresh();act(s,'dispatch');const progress=structuredClone(s.progress),r=C.offline(s,epoch+86400000);assert.equal(r.seconds,43200);assert.ok(r.gold>0&&r.xp>0);assert.deepEqual(s.progress,progress);const resources=structuredClone(s.resources),rng=s.rng;assert.equal(C.offline(s,epoch+86400000).gold,0);assert.deepEqual(s.resources,resources);assert.equal(s.rng,rng);assert.equal(s.materials.myth,0);assert.equal(s.materials.void,0);});
test('offline subtracts remaining rest and segments potion expiry/weekend',()=>{const a=fresh(),b=structuredClone(a);a.hunting.restUntil=epoch+20000;a.hunting.autoContinue=true;b.hunting.active=true;const ra=C.offline(a,epoch+3600000),rb=C.offline(b,epoch+3600000);assert.ok(ra.gold<rb.gold&&ra.gold>rb.gold*.9);const c=fresh(),d=structuredClone(c);c.hunting.active=d.hunting.active=true;c.buffs.gold=epoch+1800000;const rc=C.offline(c,epoch+3600000),rd=C.offline(d,epoch+3600000);assert.ok(rc.gold>rd.gold);assert.ok(rc.gold<rd.gold*1.5);});
test('offline attack potion exactly expires instead of multiplying whole period',()=>{const a=fresh(),b=structuredClone(a);a.hunting.active=b.hunting.active=true;a.buffs.attack=epoch+1800000;const ra=C.offline(a,epoch+3600000),rb=C.offline(b,epoch+3600000);assert.ok(ra.gold>rb.gold);assert.ok(ra.gold<rb.gold*1.3);});
test('ascension preserves permanent currency, first clears, RNG continuity and resets run',()=>{const s=fresh();cash(s);s.progress.zone=7;s.progress.stage=10;s.progress.maxZone=9;s.progress.maxStage=5;s.progress.firstClears=[1,2,3];s.buildings.castle=s.buildings.tavern=s.buildings.training=10;s.ext.permanent={claimed:'starter'};const permanent={gems:s.resources.gems,tickets:s.resources.tickets,books:s.resources.books};unchanged(s,'ascend',{});const rng=s.rng;assert.equal(act(s,'ascend',{confirm:true}).ok,true);assert.equal(s.ascensions,1);assert.equal(s.traditionChoices,1);assert.equal(s.resources.gold,300);assert.equal(s.resources.gems,permanent.gems);assert.equal(s.resources.tickets,permanent.tickets);assert.equal(s.resources.books,permanent.books);assert.equal(s.heroes.length,1);assert.equal(s.heroes[0].stars,2);assert.equal(s.heroes[0].level,1);assert.deepEqual(s.progress.firstClears,[1,2,3]);assert.equal(s.progress.maxZone,9);assert.equal(s.progress.zone,1);assert.equal(s.hunting.active,false);assert.notEqual(s.rng,rng);assert.deepEqual(s.ext.permanent,{claimed:'starter'});assert.equal(act(s,'tradition',{id:'hunting'}).ok,true);unchanged(s,'tradition',{id:'academic'});unchanged(s,'ascend',{confirm:true});assert.equal(C.validate(s).ok,true);});
test('save rejects malformed, duplicate and incompatible equipment identities',()=>{const s=fresh();assert.equal(C.validate({version:1}).ok,false);s.teams[0][1]=s.teams[0][0];assert.equal(C.validate(s).ok,false);s.teams[0][1]=null;s.resources.gold=-1;assert.equal(C.validate(s).ok,false);s.resources.gold=10;s.heroes[0].equipment.weapon='missing';assert.equal(C.validate(s).ok,false);});
test('material conversion cannot turn same tier/backwards into free resources',()=>{const s=fresh();cash(s);unchanged(s,'convertMaterial',{from:'iron',to:'herb'});unchanged(s,'convertMaterial',{from:'void',to:'iron'});const gold=s.resources.gold,iron=s.materials.iron;assert.equal(act(s,'convertMaterial',{from:'iron',to:'crystal',count:3}).count,3);assert.equal(s.resources.gold,gold-300);assert.equal(s.materials.iron,iron-12);});
test('fixed-step battle outcomes match splitting real elapsed time',()=>{const a=fresh(1337),b=structuredClone(a);act(a,'dispatch');act(b,'dispatch');hunt(a,30);for(let i=0;i<300;i++)hunt(b,.1);assert.deepEqual(a.resources,b.resources);assert.equal(a.rng,b.rng);assert.equal(a.stats.kills,b.stats.kills);assert.deepEqual(a.progress,b.progress);});
test('crafting follows current region unlocks and weapon class restriction',()=>{const s=fresh();s.resources.gold=10000;s.materials.iron=100;s.materials.crystal=100;assert.equal(act(s,'craft',{recipeId:'steel-sword'}).ok,true);const it=s.inventory.at(-1);assert.equal(it.tier,2);assert.equal(it.classId,'swordsman');assert.ok(it.stars>=2);assert.equal(it.holes,it.gems.length);unchanged(s,'craft',{recipeId:'fine-helmet'});const mage=add(s,'mage');unchanged(s,'equip',{heroId:mage.id,itemId:it.id});});
test('only selected main and sub skills cast; insufficient mana has no cooldown',()=>{const s=fresh();cash(s);const h=add(s,'mage',3,25);s.teams[0]=[h.id,null,null,null,null];h.mainSkill=0;h.subSkill=2;act(s,'dispatch');engage(s);s.hunting.enemy.hp=s.hunting.enemy.maxHp=1e8;h.mp=0;hunt(s,.1);assert.deepEqual(h.cooldowns,[0,0,0]);h.mp=C.heroStats(s,h).maxMp;hunt(s,.1);assert.ok(h.cooldowns[0]>0&&h.cooldowns[2]>0);assert.equal(h.cooldowns[1],0);assert.equal(s.hunting.enemy.dots.length,1);});
test('DOT sources coexist, effective damage and healing never exceed actual pools',()=>{const s=fresh();cash(s);const a=add(s,'mage',3,25),b=add(s,'mage',3,25);s.teams[0]=[a.id,b.id,null,null,null];act(s,'dispatch');engage(s);s.hunting.enemy.hp=s.hunting.enemy.maxHp=1e8;hunt(s,.1);assert.equal(s.hunting.enemy.dots.length,2);assert.notEqual(s.hunting.enemy.dots[0].key,s.hunting.enemy.dots[1].key);const t=fresh();const h=t.heroes[0];act(t,'dispatch');engage(t);t.hunting.enemy.hp=1;h.attackTimer=10;hunt(t,.1);assert.equal(t.hunting.report[h.id].damage,1);for(const ev of t.events.filter(e=>e.type==='heal'))assert.ok(ev.amount<=C.heroStats(t,h).maxHp);});
test('boss shield halves attacks, regen heals under half, freezing stops enemy attacks',()=>{const a=fresh(700),b=structuredClone(a);act(a,'dispatch');act(b,'dispatch');engage(a);engage(b);for(const s of[a,b]){s.hunting.enemy.hp=s.hunting.enemy.maxHp=100000;s.heroes[0].attackTimer=10;}a.hunting.enemy.mechanic='shield';hunt(a,.1);hunt(b,.1);assert.ok(Math.abs(a.hunting.report[a.heroes[0].id].damage*2-b.hunting.report[b.heroes[0].id].damage)<1e-6);const c=fresh();act(c,'dispatch');engage(c);const e=c.hunting.enemy;e.mechanic='regen';e.hp=e.maxHp*.4;const hp=e.hp;hunt(c,.1);assert.ok(e.hp>hp);e.freeze=2;e.attackTimer=100;const before=c.heroes[0].hp;hunt(c,.1);assert.equal(c.heroes[0].hp,before);assert.ok(e.freeze<2);});
test('all ten regions and eighteen skills have actual content metadata',()=>{assert.equal(D.zones.length,10);assert.equal(D.zones.reduce((n,z)=>n+z.monsters.length,0),50);assert.equal(D.skills.length,18);assert.equal(D.recipes.length,13);for(const z of D.zones){assert.ok(z.boss.name);assert.ok(C.enemyPreview(fresh(),z.id,10,0).hp>z.boss.hp);}assert.equal(Object.keys(D.sets).length,6);});
test('extension integration is deterministic across batched tick sizes and validates imports',()=>{const s=fresh(42);const E=require('../js/game-extensions.js');global.GameExtensions=E;E.init(s,s.clock);const b=structuredClone(s);act(s,'dispatch');act(b,'dispatch');hunt(s,60);for(let i=0;i<600;i++)hunt(b,.1);assert.equal(s.rng,b.rng);assert.deepEqual(s.resources,b.resources);assert.equal(C.validate(s).ok,true);s.ext.artifacts.dragon={level:100,awakening:0};assert.equal(C.validate(s).ok,false);delete global.GameExtensions;});
test('import rejects missing counters and timers before combat can create NaN',()=>{
  const mutations=[
    s=>delete s.kingdom.xp,
    s=>delete s.stats.kills,
    s=>delete s.heroes[0].attackTimer,
    s=>s.heroes[0].status.guard='invalid',
    s=>delete s.hunting.focusSeconds,
    s=>delete s.autoPotion.nextAt,
    s=>delete s.consumables.hp,
    s=>delete s.buffs.gold,
    s=>delete s.hunting.enemy.mechanicTimer,
    s=>s.hunting.enemy.dots.push({key:'invalid',heroId:s.heroes[0].id,remaining:3,timer:0}),
    s=>s.hunting.report[s.heroes[0].id]={damage:5},
    s=>delete s.gameplaySeed
  ];
  for(const mutate of mutations){const s=fresh();act(s,'dispatch');assert.equal(C.validate(s).ok,true);mutate(s);assert.equal(C.validate(s).ok,false,String(mutate));}
});
test('import rejects rewound identity sequence and duplicate event identities',()=>{
  const s=fresh();s.sequence=0;assert.equal(C.validate(s).ok,false);
  const events=fresh();C.log(events,'first');C.log(events,'second');events.events[1].id=events.events[0].id;assert.equal(C.validate(events).ok,false);
  const loot=fresh();loot.inventory.push(C.makeItem(loot,3));loot.sequence--;assert.equal(C.validate(loot).ok,false);
});
test('in-progress skill battle survives JSON save and preserves deterministic continuation',()=>{
  const a=fresh(834),mage=add(a,'mage',3,25);a.teams[0]=[mage.id,null,null,null,null];act(a,'dispatch');engage(a);a.hunting.enemy.hp=a.hunting.enemy.maxHp=1e8;hunt(a,1.25);
  assert.ok(a.hunting.enemy.dots.length);const b=JSON.parse(JSON.stringify(a));assert.equal(C.validate(b).ok,true);
  hunt(a,8.75);hunt(b,8.75);assert.equal(C.validate(b).ok,true);assert.deepEqual(b,a);
});
